#!/bin/env bash
# vim: filetype=sh

# oh my posh
if command -v oh-my-posh &>/dev/null; then
    if [ -d "$HOME/.config/ohmyposh/my_amro_colors" ]; then
        eval "$(oh-my-posh init bash --config "$HOME"/.config/ohmyposh/my_amro_colors/my_amro_colors_2.toml)"
    else
        if command -v brew &>/dev/null && [ -f "$(brew --prefix oh-my-posh)/themes/amro.omp.json" ]; then
            eval "$(oh-my-posh init zsh --config "$(brew --prefix oh-my-posh)/themes/amro.omp.json")"
        fi
    fi
fi
