#!/bin/env zsh
# vim: filetype=zsh

export PATH=$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH

# clear
alias clear='clear -x'

# sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# brightness control
if (( ${+commands[ddcutil]} )); then
    alias dcs='ddcutil setvcp 10'
fi

# ls && utils
if (( ${+commands[lsd]} )); then
    alias ls='lsd --icon=always'
    alias ll='lsd -alF --icon=always'
    alias la='lsd -A --icon=always'
    alias l='lsd -F --icon=always'
else
    alias ll='ls -alF'
    alias la='ls -A'
    alias l='ls -F'
fi

# dir
alias dir='dir --color=always'
alias vdir='vdir --color=always'

# bitwarden
if (( ${+commands[bw]} )); then
    alias ubw='export BW_SESSION=$(bw unlock --raw)'
fi

# nvim
if (( ${+commands[nvim]} )); then
    alias vim='nvim'
    alias nano='nvim'
    alias v='nvim .'

    if (( ${+commands[nano]} )); then
        alias cnano='command nano'
    fi
fi

# ufw
if (( ${+commands[ufw]} )); then
    alias _ufw_config='chmod +x "$HOME/.config/yadm/bootstrap.x.d/set_up_ufw.sh" && "$HOME/.config/yadm/bootstrap.x.d/set_up_ufw.sh"'
fi

# grep
alias grep='grep --color=always'
alias fgrep='fgrep --color=always'
alias egrep='egrep --color=always'

# tmux
if (( ${+commands[tmux]} )); then
    alias tattach='tmux attach'
    alias tds='tmux new-session -s default'
fi

# miru
if (( ${+commands[miru]} )); then
    alias mjs='miru npm'
    alias mgo='miru go'
    alias mrs='miru rs'
fi

# pacman, paru & utilities
if (( ${+commands[pacfiles]} )); then
    alias upacf='pacfiles --update-db *'
    alias pacf='pacfiles -l'
fi
alias premove='paru -Qq | fzf --multi --preview "paru -Qi {}" | xargs -r paru -Rns --noconfirm'
alias yay='paru'

# git
if (( ${+commands[git]} )); then
    alias gitGraph='git --no-pager log --oneline --graph --all --decorate --stat --color --pretty=format:"%h %d %s %an %ar"'
    alias gl='git log'

    alias gb='git branch'

    alias gmt='git mergetool --tool=nvimdiff'

    alias gcl='git clone'
    alias gcm='git commit'

    alias gpp='git push'
    alias gu='git pull'

    alias ga='git add'
    alias gap='git add --patch'
    alias gr='git restore'
    alias grs='git restore --staged'

    alias gds='git diff --staged'
    alias gd='git diff | diff-so-fancy'
fi

# yadm
if (( ${+commands[yadm]} )); then
    alias yadm_update='chmod +x "$HOME/.config/yadm/bin/yadm_update" && "$HOME/.config/yadm/bin/yadm_update"'
fi

# yazy
if (( ${+commands[yazi]} )); then
    alias y='yazi'
fi

# kitty
if (( ${+commands[kitty]} )); then
    alias icat='kitty +kitten icat'
fi

# python & utils
if (( ${+commands[python3]} )); then
    alias python='python3'
    alias jmolten='python -m ipykernel install --user --name=python3 --display-name "Python 3 (Molten)"'
fi
if (( ${+commands[direnv]} )); then
    alias da='direnv allow'
fi
alias jupywatch='watchmedo shell-command --patterns="*.py" --command="jupytext --sync \${watch_src_path}"'

# cat | bat
if (( ${+commands[bat]} )); then
    alias cat='bat --paging=never --style=plain'
    alias c='bat --paging=never'
fi

# man & utilities
if (( ${+commands[qman]} )); then
    alias man='qman'
    alias cman='command man'
fi

# psql
if (( ${+commands[psql]} )); then
    alias spsql='sudo systemctl start postgresql && sudo -u postgres psql'
    alias kpsql='sudo systemctl stop postgresql'
fi

# some more aliases
if (( ${+commands[grip]} )); then
    alias renderMarkdown='grip'
fi
alias chgra='chmod +x gradlew'
