#!/bin/env zsh
# vim: filetype=zsh

lsd_widget() { lsd -F }
yazi_widget() { yazi }
fk_widget() { fk }
fe_widget() { fe }
sesh_connect_widget() { sesh_connect }

zle -N lsd_widget
zle -N yazi_widget
zle -N fk_widget
zle -N fe_widget
zle -N sesh_connect_widget
zle -N select-quoted

bindkey "\eg" lsd_widget    # Alt+g
bindkey "\ey" yazi_widget   # Alt+y
bindkey "^O" fe_widget      # Ctrl+o
# bindkey "\eb" pf_widget    # Alt+b 
# bindkey "^F" new_ss_widget # Ctrl+f 
# bindkey "^A" fs_widget     # Ctrl+a 

# Completion settings
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^B' yank
bindkey '^D' delete-char
bindkey '^W' backward-kill-word
bindkey '^H' backward-kill-word
bindkey '\ed' kill-word
bindkey '\eb' backward-word
bindkey '\ef' forward-word
bindkey '^L' clear-screen
bindkey '^K' kill-line
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# Home/End
bindkey '\e[H' beginning-of-line   # Home
bindkey '\e[F' end-of-line         # End
bindkey '\e[1~' beginning-of-line  # Alternative home 
bindkey '\e[4~' end-of-line        # Alternative End 
bindkey '\eOH' beginning-of-line   # Some xterms
bindkey '\eOF' end-of-line

# Completion & history
bindkey '^Y' autosuggest-accept
bindkey '^I' expand-or-complete
bindkey '\e[Z' reverse-menu-complete
bindkey '\e[A' history-search-backward
bindkey '\e[B' history-search-forward

# Others
bindkey '\e.' yank-last-arg

# Quoted vi edition
autoload -U __vi-select-quoted
zle -N __vi-select-quoted
for m in visual viopp; do
    for c in {a,i}{\',\",\`}; do
        bindkey -M $m $c __vi-select-quoted
    done
done

# vi mode
bindkey -v
