#!/bin/env zsh
# vim: filetype=zsh

export PATH="$HOME/go/bin:$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH"

# --------------- Completions Directories ---------------

_COMPLETIONS_DIR="$HOME/.config/zsh/completions"
_GENERATED_COMPLETIONS_DIR="$_COMPLETIONS_DIR/generated"
_MANUAL_COMPLETIONS_DIR="$_COMPLETIONS_DIR/manual"
mkdir -p "$_COMPLETIONS_DIR"
mkdir -p "$_GENERATED_COMPLETIONS_DIR"
mkdir -p "$_MANUAL_COMPLETIONS_DIR"

# ---------------- Generated Completions ----------------

# bootdev completions
if (( ${+commands[bootdev]} )); then
    if [ ! -f "$_GENERATED_COMPLETIONS_DIR/_bootdev" ]; then
        bootdev completion zsh > "$_GENERATED_COMPLETIONS_DIR/_bootdev"
    fi
fi

# eww completions
if (( ${+commands[eww]} )); then
    if [ ! -f "$_GENERATED_COMPLETIONS_DIR/_eww" ]; then
        eww shell-completions --shell zsh > "$_GENERATED_COMPLETIONS_DIR/_eww"
    fi
fi

# mdcat completions
if (( ${+commands[eww]} )); then
    if [ ! -f "$_GENERATED_COMPLETIONS_DIR/_mdcat" ]; then
        mdcat --completions zsh > "$_GENERATED_COMPLETIONS_DIR/_mdcat"
    fi
fi

# git-bug completions
if (( ${+commands[git-bug]} )); then
    if [ ! -f "$_GENERATED_COMPLETIONS_DIR/_git-bug" ]; then
        git-bug completion zsh > "$_GENERATED_COMPLETIONS_DIR/_git-bug"
    fi
fi

# -------------------------------------------------------

fpath=(
    "$_GENERATED_COMPLETIONS_DIR"
    "$_MANUAL_COMPLETIONS_DIR"
    "$HOME/.config/zsh/plugins/zsh-completions/src"
    $fpath
)
