#!/usr/bin/env zsh
# ~/.config/zsh/.zshrc

# History settings
HISTSIZE=10000
SAVEHIST=10000
HISTFILESIZE=2000
HISTTIMEFORMAT='%m-%d %T '
HISTDUP=erase

# Avoid exiting with Ctrl+D
export IGNOREEOF=999

# Virtualenv home
export VENV_HOME="$HOME/.virtualenvs"
[[ -d $VENV_HOME ]] || mkdir -p $VENV_HOME

# Prompt/Project
export MY_PROJECT_PATH="$PWD"

# Pager
export PAGER='less'
export LESS='-FRX'
export MANPAGER='less -RX'

# Themes
export BAT_THEME="Catppuccin Mocha"
export HYPRCURSOR_THEME="Bibata-Modern-Classic"

# Hyprshot
export HYPRSHOT_DIR="$HOME/Pictures/screenshots/"

# Browser
export BROWSER='zen-browser'

# Editor
export EDITOR='nvim'

# Terminal
export TERMINAL="kitty"

# GCC colors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Disable next telemetry
export NEXT_TELEMETRY_DISABLED=1
