#!/bin/env zsh
# vim: filetype=zsh

export PATH=$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH

export FZF_ALT_C_COMMAND=
if (( ${+commands[fzf]} )); then
    if [[ ! -f ~/.cache/fzf.zsh ]]; then
        fzf --zsh > ~/.cache/fzf.zsh
    fi
    source ~/.cache/fzf.zsh
fi

export FZF_DEFAULT_COMMAND="fd \
    --ansi \
    --bind ctrl-y:accept \
    --hidden \
    --strip-cwd-prefix \
    --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS=" \
    --ansi \
    --bind ctrl-y:accept \
    --color=bg+:#363A4F,bg:#24273A,spinner:#F4DBD6,hl:#ED8796 \
    --color=fg:#CAD3F5,header:#ED8796,info:#C6A0F6,pointer:#F4DBD6 \
    --color=marker:#B7BDF8,fg+:#CAD3F5,prompt:#C6A0F6,hl+:#ED8796 \
    --color=selected-bg:#494D64 \
    --color=border:#6E738D,label:#CAD3F5
"
export FZF_COMPLETION_TRIGGER='__'

_fzf_compgen_path() {
	fd --hidden --exclude .git ."$1"
}

_fzf_compgen_dir() {
	fd --type d --hidden --exclude .git . "$1"
}

export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range :500 {}'"
export FZF_ALT_C_OPTS="--preview 'lsd --icons always --tree --depth 2 -F {}'"

_fzf_comprun() {
    local command=$1
    shift

    case "$command" in
    cd)
        fzf  \
            --preview 'lsd --icons always --tree --depth 2 -F {}' "$@"
        ;;
    export | unset)
        fzf  \
            --preview "eval 'echo \$' {}" "$@"
        ;;
    ssh)
        fzf  \
            --preview 'dig {}' "$@"
        ;;
    *)
        fzf  \
            --preview 'bat -n --color=always --line-range :500 {}' "$@"
        ;;
    esac
}

