#!/bin/env zsh
# vim: filetype=zsh


# HOMES
export ANDROID_HOME="$HOME/.AndroidS/Sdk"

# ---- PATH EXPORTS ----
if (( ${+commands[yarn]} )); then
    export PATH="$HOME/.yarn/bin:$PATH"
fi
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:/home/talinux/.dotnet/tools"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH"
export PATH="$PATH:$HOME/go/bin"
export PATH="$HOME/.phpenv/bin:$PATH"
export PATH="$PATH:$HOME/.cargo/env"
export PATH="$PATH:/var/lib/snapd/snap/bin"
export PATH="$PATH:$HOME/.config/yadm/bin"

# pnpm
export PNPM_HOME="/home/talinux/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
