#!/bin/env zsh
# vim: filetype=zsh

if (( ! ${+commands[oh-my-posh]} )); then
    exit 0
fi

if [ -d "$HOME/.config/ohmyposh/my_amro_colors" ]; then
    eval "$(oh-my-posh init zsh --config "$HOME"/.config/ohmyposh/my_amro_colors/zsh/my_amro_colors_2.toml)"
fi

