#!/bin/env zsh
# vim: filetype=zsh

export PATH=$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH

if (( ! ${+commands[oh-my-posh]} )); then
    exit 0
fi

if [ -d "$HOME/.config/ohmyposh/my_amro_colors" ]; then
    eval "$(oh-my-posh init zsh --config "$HOME"/.config/ohmyposh/my_amro_colors/my_amro_colors_2.toml)"
fi

