#!/bin/env zsh
# vim: filetype=zsh

if [ -d "$HOME/.config/ohmyposh/my_amro_colors" ]; then
    eval "$(oh-my-posh init zsh --config "$HOME"/.config/ohmyposh/my_amro_colors/my_amro_colors_2.toml)"
else
    if command -v brew >/dev/null 2>&1 && [ -f "$(brew --prefix oh-my-posh)/themes/amro.omp.json" ]; then
        eval "$(oh-my-posh init zsh --config "$(brew --prefix oh-my-posh)/themes/amro.omp.json")"
    fi
fi

