#!/bin/env zsh
# vim: filetype=zsh

# Append to the history file, don't overwrite it
setopt APPEND_HISTORY

# Save multi-line commands as a single entry in the history
setopt EXTENDED_HISTORY

# Make history shareable
setopt SHAREHISTORY

# Check window size after each command and update LINES and COLUMNS
setopt CHECK_JOBS

# Include hidden files (starting with .) in pathname expansions
setopt dotglob

# If a glob doesn't match, expand to nothing instead of the pattern itself
setopt NULL_GLOB

# Make pathname expansion case-insensitive
setopt NO_CASE_GLOB

# Expand variables in the prompt (PS1) each time it is displayed
setopt PROMPT_SUBST

# No beep
setopt NO_BEEP

# don't put duplicate lines or lines starting with space in the history.
setopt HIST_IGNORE_ALL_DUPS  
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
