local mods = require("envs.mods")

local mainMod = mods.alt_l
local scndMod = mods.super
local shiftMod = mods.shift
local hyperMod = mods.hyper

local bind = hl.bind
local resize = hl.dsp.window.resize

bind(scndMod .. " + R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
    bind("L", function()
        resize("20 0")
    end, { repeating = true })
    bind("H", function()
        resize("-20 0")
    end, { repeating = true })
    bind("K", function()
        resize("0 -20")
    end, { repeating = true })
    bind("J", function()
        resize("0 20")
    end, { repeating = true })

    bind(mainMod .. " + L", function()
        resize("60 0")
    end, { repeating = true })
    bind(mainMod .. " + H", function()
        resize("-60 0")
    end, { repeating = true })
    bind(mainMod .. " + K", function()
        resize("0 -60")
    end, { repeating = true })
    bind(mainMod .. " + J", function()
        resize("0 60")
    end, { repeating = true })

    bind(shiftMod .. " + L", function()
        resize("120 0")
    end, { repeating = true })
    bind(shiftMod .. " + H", function()
        resize("-120 0")
    end, { repeating = true })
    bind(shiftMod .. " + K", function()
        resize("0 -120")
    end, { repeating = true })
    bind(shiftMod .. " + J", function()
        resize("0 120")
    end, { repeating = true })

    bind(scndMod .. " + L", function()
        resize("240 0")
    end, { repeating = true })
    bind(scndMod .. " + H", function()
        resize("-240 0")
    end, { repeating = true })
    bind(scndMod .. " + K", function()
        resize("0 -240")
    end, { repeating = true })
    bind(scndMod .. " + J", function()
        resize("0 240")
    end, { repeating = true })

    bind(hyperMod .. " + L", function()
        resize("500 0")
    end, { repeating = true })
    bind(hyperMod .. " + H", function()
        resize("-500 0")
    end, { repeating = true })
    bind(hyperMod .. " + K", function()
        resize("0 -500")
    end, { repeating = true })
    bind(hyperMod .. " + J", function()
        resize("0 500")
    end, { repeating = true })

    bind(scndMod .. " + R", hl.dsp.submap("reset"))
end)
