#!/usr/bin/env zsh

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# load history file before everything
HISTFILE="${XDG_CONFIG_HOME:-$HOME/.config}/zsh/history"

# load prompt before everything
if [[ -f "$HOME/.config/zsh/config/prompt" ]]; then
    source "$HOME/.config/zsh/config/prompt"
fi

stty susp undef

# --------------------- Plugins ---------------------

__source_zsh_plugins() {
    local plugins_base="$HOME/.config/zsh/plugins"
    local plugins=(
        "zsh-autosuggestions"
        "zsh-syntax-highlighting"
    )

    local plugin
    for plugin in "${plugins[@]}"; do
        if [[ -f "$plugins_base/settings/$plugin" ]]; then
            source "$plugins_base/settings/$plugin"
        elif [[ -f "$plugins_base/settings/$plugin/settings" ]]; then  
            source "$plugins_base/settings/$plugin/settings"
        fi

        local plugin_path="$plugins_base/repos/$plugin/$plugin.zsh"
        if [[ -f "$plugin_path" ]]; then  
            source "$plugin_path"
        fi
    done
}

__source_zsh_plugins
unset -f __source_zsh_plugins

# ---------------------------------------------------

__source_zsh_config_files() {
    local zsh_home="$HOME/.config/zsh"
    local files=(
        "envs"
        "aliases"
        "completions"
        "functions"
        "sources"
        "setopt"
        "binds"
        "fzf"
        "evals"
        "zstyle"
    )

    local path
    for file in "${files[@]}"; do
        path="$zsh_home/config/$file"
        if [[ -f $path ]]; then
            source "$path"
        fi
    done
}

__source_zsh_config_files
unset -f __source_zsh_config_files

__source_zsh_secrets() {
    local zsh_home="$HOME/.config/zsh"
    
    local files=(
        "tokens"
    )

    local path
    for file in "${files[@]}"; do
        path="$zsh_home/secrets/$file"
        if [[ -f $path ]]; then
            source "$path"
        fi
    done
}

__source_zsh_secrets
unset -f __source_zsh_secrets

autoload -Uz compinit && compinit

# -------------------- Main file specifics --------------------

# PATH
if (( ${+commands[npm]} )); then
    prefix=$(npm config get prefix 2>/dev/null)
    if [[ -n "$prefix" ]]; then
        path=("$prefix/bin" $path)
    fi
fi

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# proto activation needs to be on main file
if (( ${+commands[proto]} )); then
    eval "$(proto activate zsh)"
fi

# export NVM_DIR="$HOME/.config/nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# -------------------------------------------------------------
