exclude = []
include = ["*"]

[formatting]
    align_comments      = true
    align_entries       = true
    allowed_blank_lines = 1
    indent_entries      = true
    indent_string       = "    "
    reorder_arrays      = true
    reorder_keys        = true
