exclude = []
include = ["*.toml"]

[formatting]
    align_comments        = true
    align_entries         = true
    allowed_blank_lines   = 1
    indent_entries        = true
    indent_string         = "    "
    indent_tables         = true
    reorder_arrays        = true
    reorder_inline_tables = true
    reorder_keys          = true
