function update_claude_completions -d "Regenerate completions/generated/claude.fish from claude --help"
    argparse -X 0 h/help -- $argv
    or return 1

    if set -q _flag_help
        printf '%s\n' "Usage: "(status current-function) \
            "  regenerates completions/generated/claude.fish from `claude --help`"
        return 0
    end

    if not command -q claude
        echo "update_claude_completions: claude is not installed" >&2
        return 1
    end

    set -l help (claude --help 2>/dev/null)
    if test (count $help) -lt 10
        echo "update_claude_completions: could not read `claude --help`" >&2
        return 1
    end

    # Parse
    set -l sections
    set -l specs
    set -l descriptions

    set -l section ""
    set -l spec ""
    set -l description ""

    for line in $help
        if string match -qr '^\S' -- $line
            if test -n "$spec"
                set -a sections $section
                set -a specs $spec
                set -a descriptions $description
            end
            set spec ""
            set description ""

            switch $line
                case Options:
                    set section options
                case Commands:
                    set section commands
                case '*'
                    set section ""
            end
            continue
        end

        test -n "$section"; or continue

        set -l entry (string match -r '^  (\S.*)$' -- $line)

        # Wrapped description
        if test (count $entry) -ne 2
            set -l wrapped (string trim -- $line)
            test -n "$spec"; and test -n "$wrapped"; and set description (string trim -- "$description $wrapped")
            continue
        end

        if test -n "$spec"
            set -a sections $section
            set -a specs $spec
            set -a descriptions $description
        end

        set -l parts (string replace -r '\s{2,}' \n -- $entry[2] | string split \n)
        set spec $parts[1]
        set description "$parts[2]"
    end

    if test -n "$spec"
        set -a sections $section
        set -a specs $spec
        set -a descriptions $description
    end

    # Emit
    set -l claude_version (claude --version 2>/dev/null | string split ' ')[1]

    set -l out \
        "# Generated by update_claude_completions from `claude --help`." \
        "# Claude Code $claude_version. Re-run that function after upgrading claude." \
        "" \
        "complete -c claude -f" \
        ""

    for i in (seq (count $specs))
        set -l spec $specs[$i]
        set -l description $descriptions[$i]

        if test (string length -- $description) -gt 110
            set description (string sub -l 107 -- $description)…
        end

        set -l flag_description
        test -n "$description"; and set flag_description " -d '"(string replace -a "'" "\\'" -- $description)"'"

        if test "$sections[$i]" = commands
            for name in (string split '|' -- (string split ' ' -- $spec)[1])
                set -a out "complete -c claude -n __fish_use_subcommand -a $name$flag_description"
            end
            continue
        end

        set -l takes_value
        string match -q '*<*' -- $spec; and set takes_value " -r"

        for flag in (string match -ar -- '(?<![\w-])--?[a-zA-Z][\w-]*' $spec)
            set -l name (string replace -r '^-+' '' -- $flag)
            set -l kind -l
            string match -qr '^-[^-]$' -- $flag; and set kind -s

            set -a out "complete -c claude $kind $name$flag_description$takes_value"
        end
    end

    # Write
    set -l generated_dir "$__fish_config_dir/completions/generated"
    mkdir -p "$generated_dir"

    set -l target "$generated_dir/claude.fish"
    printf '%s\n' $out >"$target"

    if not fish -n "$target"
        rm -f "$target"
        echo "update_claude_completions: generated file was invalid, discarded" >&2
        return 1
    end
end
