/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Generated at: 2024-10-09 09:01:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package jsp.secure.views.bulkedit;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.atlassian.jira.util.BrowserUtils;

public final class bulkwatchconfirmation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.atlassian.jira.util.BrowserUtils");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fui_005fparam_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fui_005fparam_0026_005fvalue_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005ftext_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005fparam_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005fcomponent_0026_005fvalue_005ftemplate_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fui_005fparam_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fui_005fparam_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005fparam_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005fcomponent_0026_005fvalue_005ftemplate_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.release();
    _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.release();
    _005fjspx_005ftagPool_005fui_005fparam_0026_005fvalue_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname.release();
    _005fjspx_005ftagPool_005fww_005fparam_0026_005fname.release();
    _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname_005fid.release();
    _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.release();
    _005fjspx_005ftagPool_005fww_005fcomponent_0026_005fvalue_005ftemplate_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n\n\n<html>\n<head>\n\t<title>");
      if (_jspx_meth_ww_005ftext_005f0(_jspx_page_context))
        return;
      out.write("</title>\n</head>\n<body>\n    <!-- Step 4 - Bulk Operation: Confirmation for Watch -->\n    ");
      if (_jspx_meth_ui_005fsoy_005f0(_jspx_page_context))
        return;
      out.write("\n    ");
      //  ui:soy
      com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f2 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
      boolean _jspx_th_ui_005fsoy_005f2_reused = false;
      try {
        _jspx_th_ui_005fsoy_005f2.setPageContext(_jspx_page_context);
        _jspx_th_ui_005fsoy_005f2.setParent(null);
        // /secure/views/bulkedit/bulkwatchconfirmation.jsp(20,4) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ui_005fsoy_005f2.setModuleKey("'com.atlassian.auiplugin:soy'");
        // /secure/views/bulkedit/bulkwatchconfirmation.jsp(20,4) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ui_005fsoy_005f2.setTemplate("'aui.page.pagePanel'");
        int _jspx_eval_ui_005fsoy_005f2 = _jspx_th_ui_005fsoy_005f2.doStartTag();
        if (_jspx_eval_ui_005fsoy_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_ui_005fsoy_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fsoy_005f2);
          }
          do {
            out.write("\n        ");
            if (_jspx_meth_ui_005fparam_005f2(_jspx_th_ui_005fsoy_005f2, _jspx_page_context))
              return;
            out.write("\n        ");
            //  ui:param
            webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f3 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
            boolean _jspx_th_ui_005fparam_005f3_reused = false;
            try {
              _jspx_th_ui_005fparam_005f3.setPageContext(_jspx_page_context);
              _jspx_th_ui_005fparam_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f2);
              // /secure/views/bulkedit/bulkwatchconfirmation.jsp(22,8) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_ui_005fparam_005f3.setName("'content'");
              int _jspx_eval_ui_005fparam_005f3 = _jspx_th_ui_005fparam_005f3.doStartTag();
              if (_jspx_eval_ui_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                if (_jspx_eval_ui_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fparam_005f3);
                }
                do {
                  out.write("\n            ");
                  if (_jspx_meth_ui_005fsoy_005f3(_jspx_th_ui_005fparam_005f3, _jspx_page_context))
                    return;
                  out.write("\n            ");
                  //  ui:soy
                  com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f4 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
                  boolean _jspx_th_ui_005fsoy_005f4_reused = false;
                  try {
                    _jspx_th_ui_005fsoy_005f4.setPageContext(_jspx_page_context);
                    _jspx_th_ui_005fsoy_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f3);
                    // /secure/views/bulkedit/bulkwatchconfirmation.jsp(28,12) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_ui_005fsoy_005f4.setModuleKey("'com.atlassian.auiplugin:soy'");
                    // /secure/views/bulkedit/bulkwatchconfirmation.jsp(28,12) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_ui_005fsoy_005f4.setTemplate("'aui.page.pagePanelContent'");
                    int _jspx_eval_ui_005fsoy_005f4 = _jspx_th_ui_005fsoy_005f4.doStartTag();
                    if (_jspx_eval_ui_005fsoy_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                      if (_jspx_eval_ui_005fsoy_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                        out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fsoy_005f4);
                      }
                      do {
                        out.write("\n                ");
                        //  ui:param
                        webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f5 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
                        boolean _jspx_th_ui_005fparam_005f5_reused = false;
                        try {
                          _jspx_th_ui_005fparam_005f5.setPageContext(_jspx_page_context);
                          _jspx_th_ui_005fparam_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f4);
                          // /secure/views/bulkedit/bulkwatchconfirmation.jsp(29,16) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_ui_005fparam_005f5.setName("'content'");
                          int _jspx_eval_ui_005fparam_005f5 = _jspx_th_ui_005fparam_005f5.doStartTag();
                          if (_jspx_eval_ui_005fparam_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            if (_jspx_eval_ui_005fparam_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fparam_005f5);
                            }
                            do {
                              out.write("\n                    ");
                              if (_jspx_meth_ui_005fsoy_005f5(_jspx_th_ui_005fparam_005f5, _jspx_page_context))
                              return;
                              out.write("\n\n                    <p>\n                        ");
                              if (_jspx_meth_ww_005ftext_005f4(_jspx_th_ui_005fparam_005f5, _jspx_page_context))
                              return;
                              out.write("\n                    </p>\n\n                    ");
                              //  page:applyDecorator
                              com.atlassian.jira.web.tags.JiraApplyDecoratorTag _jspx_th_page_005fapplyDecorator_005f0 = (com.atlassian.jira.web.tags.JiraApplyDecoratorTag) _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname_005fid.get(com.atlassian.jira.web.tags.JiraApplyDecoratorTag.class);
                              boolean _jspx_th_page_005fapplyDecorator_005f0_reused = false;
                              try {
                              _jspx_th_page_005fapplyDecorator_005f0.setPageContext(_jspx_page_context);
                              _jspx_th_page_005fapplyDecorator_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f5);
                              // /secure/views/bulkedit/bulkwatchconfirmation.jsp(46,20) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_page_005fapplyDecorator_005f0.setId("bulkwatch");
                              // /secure/views/bulkedit/bulkwatchconfirmation.jsp(46,20) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_page_005fapplyDecorator_005f0.setName("auiform");
                              int _jspx_eval_page_005fapplyDecorator_005f0 = _jspx_th_page_005fapplyDecorator_005f0.doStartTag();
                              if (_jspx_eval_page_005fapplyDecorator_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                              if (_jspx_eval_page_005fapplyDecorator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_page_005fapplyDecorator_005f0);
                              }
                              do {
                              out.write("\n                        ");
                              if (_jspx_meth_page_005fparam_005f0(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
                              return;
                              out.write("\n                        ");
                              if (_jspx_meth_page_005fparam_005f1(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
                              return;
                              out.write("\n\n                        <p>\n                            <input class=\"aui-button\" id=\"confirm\" type=\"submit\" name=\"");
                              if (_jspx_meth_ww_005ftext_005f5(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
                              return;
                              out.write("\" value=\"");
                              if (_jspx_meth_ww_005ftext_005f6(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
                              return;
                              out.write("\"\n                                accessKey=\"");
                              if (_jspx_meth_ww_005ftext_005f7(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
                              return;
                              out.write("\"\n                                title=\"");
                              //  ww:text
                              com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f8 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname.get(com.atlassian.jira.web.tags.TextTag.class);
                              boolean _jspx_th_ww_005ftext_005f8_reused = false;
                              try {
                              _jspx_th_ww_005ftext_005f8.setPageContext(_jspx_page_context);
                              _jspx_th_ww_005ftext_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
                              // /secure/views/bulkedit/bulkwatchconfirmation.jsp(53,39) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_ww_005ftext_005f8.setName("'common.forms.submit.tooltip'");
                              int _jspx_eval_ww_005ftext_005f8 = _jspx_th_ww_005ftext_005f8.doStartTag();
                              if (_jspx_eval_ww_005ftext_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                              if (_jspx_eval_ww_005ftext_005f8 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ww_005ftext_005f8);
                              }
                              do {
                              out.write("\n                                ");
                              if (_jspx_meth_ww_005fparam_005f1(_jspx_th_ww_005ftext_005f8, _jspx_page_context))
                              return;
                              out.write("\n                                ");
                              //  ww:param
                              webwork.view.taglib.ParamTag _jspx_th_ww_005fparam_005f2 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fww_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
                              boolean _jspx_th_ww_005fparam_005f2_reused = false;
                              try {
                              _jspx_th_ww_005fparam_005f2.setPageContext(_jspx_page_context);
                              _jspx_th_ww_005fparam_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005ftext_005f8);
                              // /secure/views/bulkedit/bulkwatchconfirmation.jsp(55,32) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_ww_005fparam_005f2.setName("'value1'");
                              int _jspx_eval_ww_005fparam_005f2 = _jspx_th_ww_005fparam_005f2.doStartTag();
                              if (_jspx_eval_ww_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                              if (_jspx_eval_ww_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ww_005fparam_005f2);
                              }
                              do {
                              out.print(BrowserUtils.getModifierKey());
                              int evalDoAfterBody = _jspx_th_ww_005fparam_005f2.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                              } while (true);
                              if (_jspx_eval_ww_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                              }
                              }
                              if (_jspx_th_ww_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                              return;
                              }
                              _005fjspx_005ftagPool_005fww_005fparam_0026_005fname.reuse(_jspx_th_ww_005fparam_005f2);
                              _jspx_th_ww_005fparam_005f2_reused = true;
                              } finally {
                              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fparam_005f2, _jsp_getInstanceManager(), _jspx_th_ww_005fparam_005f2_reused);
                              }
                              out.write("\n                                ");
                              int evalDoAfterBody = _jspx_th_ww_005ftext_005f8.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                              } while (true);
                              if (_jspx_eval_ww_005ftext_005f8 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                              }
                              }
                              if (_jspx_th_ww_005ftext_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                              return;
                              }
                              _005fjspx_005ftagPool_005fww_005ftext_0026_005fname.reuse(_jspx_th_ww_005ftext_005f8);
                              _jspx_th_ww_005ftext_005f8_reused = true;
                              } finally {
                              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f8, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f8_reused);
                              }
                              out.write("\"\n                            />\n                            <a class=\"aui-button aui-button-link\" id=\"cancel\" href=\"");
                              out.print( request.getContextPath() );
                              out.write("/secure/BulkCancelWizard.jspa\">");
                              if (_jspx_meth_ww_005ftext_005f10(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
                              return;
                              out.write("</a>\n                        </p>\n\n                        ");
                              if (_jspx_meth_ww_005fcomponent_005f0(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
                              return;
                              out.write("\n                    ");
                              int evalDoAfterBody = _jspx_th_page_005fapplyDecorator_005f0.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                              } while (true);
                              if (_jspx_eval_page_005fapplyDecorator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                              }
                              }
                              if (_jspx_th_page_005fapplyDecorator_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                              return;
                              }
                              _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname_005fid.reuse(_jspx_th_page_005fapplyDecorator_005f0);
                              _jspx_th_page_005fapplyDecorator_005f0_reused = true;
                              } finally {
                              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_page_005fapplyDecorator_005f0, _jsp_getInstanceManager(), _jspx_th_page_005fapplyDecorator_005f0_reused);
                              }
                              out.write("\n                ");
                              int evalDoAfterBody = _jspx_th_ui_005fparam_005f5.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                            if (_jspx_eval_ui_005fparam_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                            }
                          }
                          if (_jspx_th_ui_005fparam_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                          _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f5);
                          _jspx_th_ui_005fparam_005f5_reused = true;
                        } finally {
                          org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f5, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f5_reused);
                        }
                        out.write("\n            ");
                        int evalDoAfterBody = _jspx_th_ui_005fsoy_005f4.doAfterBody();
                        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                          break;
                      } while (true);
                      if (_jspx_eval_ui_005fsoy_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                        out = _jspx_page_context.popBody();
                      }
                    }
                    if (_jspx_th_ui_005fsoy_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f4);
                    _jspx_th_ui_005fsoy_005f4_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fsoy_005f4, _jsp_getInstanceManager(), _jspx_th_ui_005fsoy_005f4_reused);
                  }
                  out.write("\n        ");
                  int evalDoAfterBody = _jspx_th_ui_005fparam_005f3.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
                if (_jspx_eval_ui_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.popBody();
                }
              }
              if (_jspx_th_ui_005fparam_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f3);
              _jspx_th_ui_005fparam_005f3_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f3, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f3_reused);
            }
            out.write("\n    ");
            int evalDoAfterBody = _jspx_th_ui_005fsoy_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_ui_005fsoy_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_ui_005fsoy_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f2);
        _jspx_th_ui_005fsoy_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fsoy_005f2, _jsp_getInstanceManager(), _jspx_th_ui_005fsoy_005f2_reused);
      }
      out.write("\n</body>\n</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_ww_005ftext_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f0 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f0_reused = false;
    try {
      _jspx_th_ww_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f0.setParent(null);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(7,8) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f0.setName("'bulkedit.title'");
      int _jspx_eval_ww_005ftext_005f0 = _jspx_th_ww_005ftext_005f0.doStartTag();
      if (_jspx_th_ww_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f0);
      _jspx_th_ww_005ftext_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f0, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fsoy_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:soy
    com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f0 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
    boolean _jspx_th_ui_005fsoy_005f0_reused = false;
    try {
      _jspx_th_ui_005fsoy_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fsoy_005f0.setParent(null);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(11,4) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fsoy_005f0.setModuleKey("'com.atlassian.auiplugin:soy'");
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(11,4) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fsoy_005f0.setTemplate("'aui.page.pageHeader'");
      int _jspx_eval_ui_005fsoy_005f0 = _jspx_th_ui_005fsoy_005f0.doStartTag();
      if (_jspx_eval_ui_005fsoy_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ui_005fsoy_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fsoy_005f0);
        }
        do {
          out.write("\n        ");
          if (_jspx_meth_ui_005fparam_005f0(_jspx_th_ui_005fsoy_005f0, _jspx_page_context))
            return true;
          out.write("\n    ");
          int evalDoAfterBody = _jspx_th_ui_005fsoy_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ui_005fsoy_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ui_005fsoy_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f0);
      _jspx_th_ui_005fsoy_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fsoy_005f0, _jsp_getInstanceManager(), _jspx_th_ui_005fsoy_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fsoy_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:param
    webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f0 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
    boolean _jspx_th_ui_005fparam_005f0_reused = false;
    try {
      _jspx_th_ui_005fparam_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f0);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(12,8) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fparam_005f0.setName("'content'");
      int _jspx_eval_ui_005fparam_005f0 = _jspx_th_ui_005fparam_005f0.doStartTag();
      if (_jspx_eval_ui_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ui_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fparam_005f0);
        }
        do {
          out.write("\n            ");
          if (_jspx_meth_ui_005fsoy_005f1(_jspx_th_ui_005fparam_005f0, _jspx_page_context))
            return true;
          out.write("\n        ");
          int evalDoAfterBody = _jspx_th_ui_005fparam_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ui_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ui_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f0);
      _jspx_th_ui_005fparam_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fsoy_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fparam_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:soy
    com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f1 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
    boolean _jspx_th_ui_005fsoy_005f1_reused = false;
    try {
      _jspx_th_ui_005fsoy_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fsoy_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f0);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(13,12) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fsoy_005f1.setModuleKey("'com.atlassian.auiplugin:soy'");
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(13,12) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fsoy_005f1.setTemplate("'aui.page.pageHeaderMain'");
      int _jspx_eval_ui_005fsoy_005f1 = _jspx_th_ui_005fsoy_005f1.doStartTag();
      if (_jspx_eval_ui_005fsoy_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ui_005fsoy_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fsoy_005f1);
        }
        do {
          out.write("\n                ");
          if (_jspx_meth_ui_005fparam_005f1(_jspx_th_ui_005fsoy_005f1, _jspx_page_context))
            return true;
          out.write("\n            ");
          int evalDoAfterBody = _jspx_th_ui_005fsoy_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ui_005fsoy_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ui_005fsoy_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f1);
      _jspx_th_ui_005fsoy_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fsoy_005f1, _jsp_getInstanceManager(), _jspx_th_ui_005fsoy_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fsoy_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:param
    webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f1 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
    boolean _jspx_th_ui_005fparam_005f1_reused = false;
    try {
      _jspx_th_ui_005fparam_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f1);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(14,16) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fparam_005f1.setName("'content'");
      int _jspx_eval_ui_005fparam_005f1 = _jspx_th_ui_005fparam_005f1.doStartTag();
      if (_jspx_eval_ui_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ui_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fparam_005f1);
        }
        do {
          out.write("\n                    <h1>");
          if (_jspx_meth_ww_005ftext_005f1(_jspx_th_ui_005fparam_005f1, _jspx_page_context))
            return true;
          out.write("</h1>\n                ");
          int evalDoAfterBody = _jspx_th_ui_005fparam_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ui_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ui_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f1);
      _jspx_th_ui_005fparam_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f1, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fparam_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f1 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f1_reused = false;
    try {
      _jspx_th_ww_005ftext_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f1);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(15,24) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f1.setName("'bulkedit.title'");
      int _jspx_eval_ww_005ftext_005f1 = _jspx_th_ww_005ftext_005f1.doStartTag();
      if (_jspx_th_ww_005ftext_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f1);
      _jspx_th_ww_005ftext_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f1, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fparam_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fsoy_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:param
    webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f2 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fvalue_005fname_005fnobody.get(webwork.view.taglib.ParamTag.class);
    boolean _jspx_th_ui_005fparam_005f2_reused = false;
    try {
      _jspx_th_ui_005fparam_005f2.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fparam_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f2);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(21,8) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fparam_005f2.setName("'id'");
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(21,8) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fparam_005f2.setValue("'stepped-process'");
      int _jspx_eval_ui_005fparam_005f2 = _jspx_th_ui_005fparam_005f2.doStartTag();
      if (_jspx_th_ui_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_ui_005fparam_005f2);
      _jspx_th_ui_005fparam_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f2, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fsoy_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fparam_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  ui:soy
    com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f3 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
    boolean _jspx_th_ui_005fsoy_005f3_reused = false;
    try {
      _jspx_th_ui_005fsoy_005f3.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fsoy_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f3);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(23,12) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fsoy_005f3.setModuleKey("'com.atlassian.auiplugin:soy'");
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(23,12) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fsoy_005f3.setTemplate("'aui.page.pagePanelNav'");
      int _jspx_eval_ui_005fsoy_005f3 = _jspx_th_ui_005fsoy_005f3.doStartTag();
      if (_jspx_eval_ui_005fsoy_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ui_005fsoy_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fsoy_005f3);
        }
        do {
          out.write("\n                ");
          if (_jspx_meth_ui_005fparam_005f4(_jspx_th_ui_005fsoy_005f3, _jspx_page_context))
            return true;
          out.write("\n            ");
          int evalDoAfterBody = _jspx_th_ui_005fsoy_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ui_005fsoy_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ui_005fsoy_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f3);
      _jspx_th_ui_005fsoy_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fsoy_005f3, _jsp_getInstanceManager(), _jspx_th_ui_005fsoy_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fparam_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fsoy_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  ui:param
    webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f4 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
    boolean _jspx_th_ui_005fparam_005f4_reused = false;
    try {
      _jspx_th_ui_005fparam_005f4.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fparam_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f3);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(24,16) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fparam_005f4.setName("'content'");
      int _jspx_eval_ui_005fparam_005f4 = _jspx_th_ui_005fparam_005f4.doStartTag();
      if (_jspx_eval_ui_005fparam_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ui_005fparam_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fparam_005f4);
        }
        do {
          out.write("\n                    ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/secure/views/bulkedit/bulkedit_leftpane.jsp", out, false);
          out.write("\n                ");
          int evalDoAfterBody = _jspx_th_ui_005fparam_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ui_005fparam_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ui_005fparam_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f4);
      _jspx_th_ui_005fparam_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f4, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fsoy_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fparam_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:soy
    com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f5 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
    boolean _jspx_th_ui_005fsoy_005f5_reused = false;
    try {
      _jspx_th_ui_005fsoy_005f5.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fsoy_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f5);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(30,20) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fsoy_005f5.setModuleKey("'com.atlassian.auiplugin:soy'");
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(30,20) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fsoy_005f5.setTemplate("'aui.page.pageHeader'");
      int _jspx_eval_ui_005fsoy_005f5 = _jspx_th_ui_005fsoy_005f5.doStartTag();
      if (_jspx_eval_ui_005fsoy_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ui_005fsoy_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fsoy_005f5);
        }
        do {
          out.write("\n                        ");
          if (_jspx_meth_ui_005fparam_005f6(_jspx_th_ui_005fsoy_005f5, _jspx_page_context))
            return true;
          out.write("\n                    ");
          int evalDoAfterBody = _jspx_th_ui_005fsoy_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ui_005fsoy_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ui_005fsoy_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f5);
      _jspx_th_ui_005fsoy_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fsoy_005f5, _jsp_getInstanceManager(), _jspx_th_ui_005fsoy_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fparam_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fsoy_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:param
    webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f6 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
    boolean _jspx_th_ui_005fparam_005f6_reused = false;
    try {
      _jspx_th_ui_005fparam_005f6.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fparam_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f5);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(31,24) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fparam_005f6.setName("'content'");
      int _jspx_eval_ui_005fparam_005f6 = _jspx_th_ui_005fparam_005f6.doStartTag();
      if (_jspx_eval_ui_005fparam_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ui_005fparam_005f6 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fparam_005f6);
        }
        do {
          out.write("\n                            ");
          if (_jspx_meth_ui_005fsoy_005f6(_jspx_th_ui_005fparam_005f6, _jspx_page_context))
            return true;
          out.write("\n                        ");
          int evalDoAfterBody = _jspx_th_ui_005fparam_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ui_005fparam_005f6 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ui_005fparam_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f6);
      _jspx_th_ui_005fparam_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f6, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fsoy_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fparam_005f6, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:soy
    com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f6 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
    boolean _jspx_th_ui_005fsoy_005f6_reused = false;
    try {
      _jspx_th_ui_005fsoy_005f6.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fsoy_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f6);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(32,28) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fsoy_005f6.setModuleKey("'com.atlassian.auiplugin:soy'");
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(32,28) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fsoy_005f6.setTemplate("'aui.page.pageHeaderMain'");
      int _jspx_eval_ui_005fsoy_005f6 = _jspx_th_ui_005fsoy_005f6.doStartTag();
      if (_jspx_eval_ui_005fsoy_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ui_005fsoy_005f6 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fsoy_005f6);
        }
        do {
          out.write("\n                                ");
          if (_jspx_meth_ui_005fparam_005f7(_jspx_th_ui_005fsoy_005f6, _jspx_page_context))
            return true;
          out.write("\n                            ");
          int evalDoAfterBody = _jspx_th_ui_005fsoy_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ui_005fsoy_005f6 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ui_005fsoy_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f6);
      _jspx_th_ui_005fsoy_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fsoy_005f6, _jsp_getInstanceManager(), _jspx_th_ui_005fsoy_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fparam_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fsoy_005f6, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:param
    webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f7 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
    boolean _jspx_th_ui_005fparam_005f7_reused = false;
    try {
      _jspx_th_ui_005fparam_005f7.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fparam_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f6);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(33,32) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fparam_005f7.setName("'content'");
      int _jspx_eval_ui_005fparam_005f7 = _jspx_th_ui_005fparam_005f7.doStartTag();
      if (_jspx_eval_ui_005fparam_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ui_005fparam_005f7 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fparam_005f7);
        }
        do {
          out.write("\n                                    <h2>");
          if (_jspx_meth_ww_005ftext_005f2(_jspx_th_ui_005fparam_005f7, _jspx_page_context))
            return true;
          out.write(':');
          out.write(' ');
          if (_jspx_meth_ww_005ftext_005f3(_jspx_th_ui_005fparam_005f7, _jspx_page_context))
            return true;
          out.write("</h2>\n                                ");
          int evalDoAfterBody = _jspx_th_ui_005fparam_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ui_005fparam_005f7 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ui_005fparam_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f7);
      _jspx_th_ui_005fparam_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f7, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fparam_005f7, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f2 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f2_reused = false;
    try {
      _jspx_th_ww_005ftext_005f2.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f7);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(34,40) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f2.setName("'bulkedit.step4'");
      int _jspx_eval_ww_005ftext_005f2 = _jspx_th_ww_005ftext_005f2.doStartTag();
      if (_jspx_th_ww_005ftext_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f2);
      _jspx_th_ww_005ftext_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f2, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fparam_005f7, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f3 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f3_reused = false;
    try {
      _jspx_th_ww_005ftext_005f3.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f7);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(34,76) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f3.setName("'bulkedit.step4.title'");
      int _jspx_eval_ww_005ftext_005f3 = _jspx_th_ww_005ftext_005f3.doStartTag();
      if (_jspx_th_ww_005ftext_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f3);
      _jspx_th_ww_005ftext_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f3, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fparam_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f4 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f4_reused = false;
    try {
      _jspx_th_ww_005ftext_005f4.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f5);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(41,24) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f4.setName("'bulk.watch.confirmation.line1'");
      int _jspx_eval_ww_005ftext_005f4 = _jspx_th_ww_005ftext_005f4.doStartTag();
      if (_jspx_eval_ww_005ftext_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ww_005ftext_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ww_005ftext_005f4);
        }
        do {
          out.write("\n                            ");
          if (_jspx_meth_ww_005fparam_005f0(_jspx_th_ww_005ftext_005f4, _jspx_page_context))
            return true;
          out.write("\n                        ");
          int evalDoAfterBody = _jspx_th_ww_005ftext_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ww_005ftext_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ww_005ftext_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname.reuse(_jspx_th_ww_005ftext_005f4);
      _jspx_th_ww_005ftext_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f4, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005ftext_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:param
    webwork.view.taglib.ParamTag _jspx_th_ww_005fparam_005f0 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fww_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
    boolean _jspx_th_ww_005fparam_005f0_reused = false;
    try {
      _jspx_th_ww_005fparam_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005ftext_005f4);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(42,28) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fparam_005f0.setName("'value0'");
      int _jspx_eval_ww_005fparam_005f0 = _jspx_th_ww_005fparam_005f0.doStartTag();
      if (_jspx_eval_ww_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ww_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ww_005fparam_005f0);
        }
        do {
          out.write("<strong>");
          if (_jspx_meth_ww_005fproperty_005f0(_jspx_th_ww_005fparam_005f0, _jspx_page_context))
            return true;
          out.write("</strong>");
          int evalDoAfterBody = _jspx_th_ww_005fparam_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ww_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ww_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fparam_0026_005fname.reuse(_jspx_th_ww_005fparam_005f0);
      _jspx_th_ww_005fparam_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_ww_005fparam_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fparam_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f0 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f0_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fparam_005f0);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(42,62) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f0.setValue("/bulkEditBean/selectedIssues/size");
      int _jspx_eval_ww_005fproperty_005f0 = _jspx_th_ww_005fproperty_005f0.doStartTag();
      if (_jspx_th_ww_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f0);
      _jspx_th_ww_005fproperty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f0, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_page_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:param
    com.opensymphony.module.sitemesh.taglib.page.ParamTag _jspx_th_page_005fparam_005f0 = (com.opensymphony.module.sitemesh.taglib.page.ParamTag) _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.get(com.opensymphony.module.sitemesh.taglib.page.ParamTag.class);
    boolean _jspx_th_page_005fparam_005f0_reused = false;
    try {
      _jspx_th_page_005fparam_005f0.setPageContext(_jspx_page_context);
      _jspx_th_page_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(47,24) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_page_005fparam_005f0.setName("action");
      int _jspx_eval_page_005fparam_005f0 = _jspx_th_page_005fparam_005f0.doStartTag();
      if (_jspx_eval_page_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_page_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_page_005fparam_005f0);
        }
        do {
          out.write("BulkWatchPerform.jspa");
          int evalDoAfterBody = _jspx_th_page_005fparam_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_page_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_page_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.reuse(_jspx_th_page_005fparam_005f0);
      _jspx_th_page_005fparam_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_page_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_page_005fparam_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_page_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:param
    com.opensymphony.module.sitemesh.taglib.page.ParamTag _jspx_th_page_005fparam_005f1 = (com.opensymphony.module.sitemesh.taglib.page.ParamTag) _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.get(com.opensymphony.module.sitemesh.taglib.page.ParamTag.class);
    boolean _jspx_th_page_005fparam_005f1_reused = false;
    try {
      _jspx_th_page_005fparam_005f1.setPageContext(_jspx_page_context);
      _jspx_th_page_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(48,24) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_page_005fparam_005f1.setName("useCustomButtons");
      int _jspx_eval_page_005fparam_005f1 = _jspx_th_page_005fparam_005f1.doStartTag();
      if (_jspx_eval_page_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_page_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_page_005fparam_005f1);
        }
        do {
          out.write("true");
          int evalDoAfterBody = _jspx_th_page_005fparam_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_page_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_page_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.reuse(_jspx_th_page_005fparam_005f1);
      _jspx_th_page_005fparam_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_page_005fparam_005f1, _jsp_getInstanceManager(), _jspx_th_page_005fparam_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f5 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f5_reused = false;
    try {
      _jspx_th_ww_005ftext_005f5.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(51,87) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f5.setName("'common.forms.confirm'");
      int _jspx_eval_ww_005ftext_005f5 = _jspx_th_ww_005ftext_005f5.doStartTag();
      if (_jspx_th_ww_005ftext_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f5);
      _jspx_th_ww_005ftext_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f5, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f6 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f6_reused = false;
    try {
      _jspx_th_ww_005ftext_005f6.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(51,136) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f6.setName("'common.forms.confirm'");
      int _jspx_eval_ww_005ftext_005f6 = _jspx_th_ww_005ftext_005f6.doStartTag();
      if (_jspx_th_ww_005ftext_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f6);
      _jspx_th_ww_005ftext_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f6, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f7 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f7_reused = false;
    try {
      _jspx_th_ww_005ftext_005f7.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(52,43) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f7.setName("'common.forms.submit.accesskey'");
      int _jspx_eval_ww_005ftext_005f7 = _jspx_th_ww_005ftext_005f7.doStartTag();
      if (_jspx_th_ww_005ftext_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f7);
      _jspx_th_ww_005ftext_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f7, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005ftext_005f8, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:param
    webwork.view.taglib.ParamTag _jspx_th_ww_005fparam_005f1 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fww_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
    boolean _jspx_th_ww_005fparam_005f1_reused = false;
    try {
      _jspx_th_ww_005fparam_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005ftext_005f8);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(54,32) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fparam_005f1.setName("'value0'");
      int _jspx_eval_ww_005fparam_005f1 = _jspx_th_ww_005fparam_005f1.doStartTag();
      if (_jspx_eval_ww_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ww_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ww_005fparam_005f1);
        }
        do {
          if (_jspx_meth_ww_005ftext_005f9(_jspx_th_ww_005fparam_005f1, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_ww_005fparam_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ww_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ww_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fparam_0026_005fname.reuse(_jspx_th_ww_005fparam_005f1);
      _jspx_th_ww_005fparam_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fparam_005f1, _jsp_getInstanceManager(), _jspx_th_ww_005fparam_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fparam_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f9 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f9_reused = false;
    try {
      _jspx_th_ww_005ftext_005f9.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fparam_005f1);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(54,58) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f9.setName("'common.forms.submit.accesskey'");
      int _jspx_eval_ww_005ftext_005f9 = _jspx_th_ww_005ftext_005f9.doStartTag();
      if (_jspx_th_ww_005ftext_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f9);
      _jspx_th_ww_005ftext_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f9, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f10 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f10_reused = false;
    try {
      _jspx_th_ww_005ftext_005f10.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(58,146) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f10.setName("'common.forms.cancel'");
      int _jspx_eval_ww_005ftext_005f10 = _jspx_th_ww_005ftext_005f10.doStartTag();
      if (_jspx_th_ww_005ftext_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f10);
      _jspx_th_ww_005ftext_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f10, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fcomponent_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:component
    webwork.view.taglib.ui.ComponentTag _jspx_th_ww_005fcomponent_005f0 = (webwork.view.taglib.ui.ComponentTag) _005fjspx_005ftagPool_005fww_005fcomponent_0026_005fvalue_005ftemplate_005fname_005fnobody.get(webwork.view.taglib.ui.ComponentTag.class);
    boolean _jspx_th_ww_005fcomponent_005f0_reused = false;
    try {
      _jspx_th_ww_005fcomponent_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fcomponent_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(61,24) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fcomponent_005f0.setName("'atl_token'");
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(61,24) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fcomponent_005f0.setValue("/xsrfToken");
      // /secure/views/bulkedit/bulkwatchconfirmation.jsp(61,24) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fcomponent_005f0.setTemplate("hidden.jsp");
      int _jspx_eval_ww_005fcomponent_005f0 = _jspx_th_ww_005fcomponent_005f0.doStartTag();
      if (_jspx_th_ww_005fcomponent_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fcomponent_0026_005fvalue_005ftemplate_005fname_005fnobody.reuse(_jspx_th_ww_005fcomponent_005f0);
      _jspx_th_ww_005fcomponent_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fcomponent_005f0, _jsp_getInstanceManager(), _jspx_th_ww_005fcomponent_005f0_reused);
    }
    return false;
  }
}
