#!/bin/bash

# credits to adi1090x

PREV_TOTAL=0
PREV_IDLE=0
cpuFile="/tmp/.cpu_usage"

get_cpu() {
    if [[ -f "${cpuFile}" ]]; then
        mapfile -t fileCont <"${cpuFile}"
        PREV_TOTAL=${fileCont[0]}
        PREV_IDLE=${fileCont[1]}
    fi

    # Read CPU stats directly from /proc/stat
    read -r -a CPU </proc/stat
    unset 'CPU[0]' # Discard the "cpu" prefix
    IDLE=${CPU[4]} # Get the idle CPU time

    # Calculate the total CPU time
    TOTAL=0
    for VALUE in "${CPU[@]:0:4}"; do
        ((TOTAL += VALUE))
    done

    if [[ -n "${PREV_TOTAL}" ]] && [[ -n "${PREV_IDLE}" ]]; then
        # Calculate the CPU usage since we last checked
        ((DIFF_IDLE = IDLE - PREV_IDLE))
        ((DIFF_TOTAL = TOTAL - PREV_TOTAL))
        ((DIFF_USAGE = (1000 * (DIFF_TOTAL - DIFF_IDLE) / DIFF_TOTAL + 5) / 10))
        echo "${DIFF_USAGE}"
    else
        echo "?"
    fi

    # Remember the total and idle CPU times for the next check
    printf "%s\n%s\n" "${TOTAL}" "${IDLE}" >"${cpuFile}"
}
get_cpu
