
gui:
  theme:
    activeBorderColor:
      - "#dcbfcb"
      - bold
    inactiveBorderColor:
      - "#d2c2c8"
    searchingActiveBorderColor:
      - "#e3bfb1"
      - bold
    optionsTextColor:
      - "#d0c3c7"
    selectedLineBgColor:
      - "#d0c3c7"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#d0c3c7"
    cherryPickedCommitBgColor:
      - "#e3bfb1"
    markedBaseCommitFgColor:
      - "#e3bfb1"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#e8e1e1"
  authorColors: {}
  branchColorPatterns: {}
  customIcons:
    filenames: {}
    extensions: {}
  scrollHeight: 2
  scrollPastBottom: true
  scrollOffMargin: 2
  scrollOffBehavior: margin
  tabWidth: 4
  mouseEvents: true
  skipAmendWarning: false
  skipDiscardChangeWarning: false
  skipStashWarning: false
  skipNoStagedFilesWarning: false
  skipRewordInEditorWarning: false
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  expandedSidePanelWeight: 2
  mainPanelSplitMode: flexible
  enlargedSideViewLocation: left
  wrapLinesInStagingView: true
  useHunkModeInStagingView: true
  language: auto
  timeFormat: 02 Jan 06
  shortTimeFormat: 3:04PM
  theme:
    activeBorderColor:
      - "#dcbfcb"
      - bold
    inactiveBorderColor:
      - "#d2c2c8"
    searchingActiveBorderColor:
      - "#e3bfb1"
      - bold
    optionsTextColor:
      - "#d0c3c7"
    selectedLineBgColor:
      - "#d0c3c7"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#d0c3c7"
    cherryPickedCommitBgColor:
      - "#e3bfb1"
    markedBaseCommitFgColor:
      - "#e3bfb1"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#e8e1e1"
  commitLength:
    show: true
  showListFooter: true
  showFileTree: true
  showRootItemInFileTree: true
  showNumstatInFilesView: false
  showRandomTip: true
  showCommandLog: true
  showBottomLine: true
  showPanelJumps: true
  nerdFontsVersion: ""
  showFileIcons: true
  commitAuthorShortLength: 2
  commitAuthorLongLength: 17
  commitHashLength: 8
  showBranchCommitHash: false
  showDivergenceFromBaseBranch: none
  commandLogSize: 8
  splitDiff: auto
  screenMode: normal
  border: rounded
  animateExplosion: true
  portraitMode: auto
  filterMode: substring
  spinner:
    frames:
      - '|'
      - /
      - '-'
      - \
    rate: 50
  statusPanelView: dashboard
  switchToFilesAfterStashPop: true
  switchToFilesAfterStashApply: true
  switchTabsWithPanelJumpKeys: false
os:
  shellFunctionsFile: ~/.config/zsh/config/aliases
