blacklist = ["scratch"]

[default_session]
startup_command = "nvim . -c \"lua require('oil').open(vim.fn.getcwd())\" -c \"lua require('telescope.builtin').find_files()\" && clear"
preview_command = "lsd --icon always --tree --depth 2 --color always {}"

[[session]]
name = "Projects 📂"
path = "~/workspace/github.com/ItzTas"
startup_command = "bash \"$HOME/.config/sesh/scripts/projects_startup.sh\""

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls -A"

[[session]]
name = "tmux config 󱂬 "
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"
