blacklist = ["scratch"]

[default_session]
startup_command = "nvim -c ':Telescope find_files'"
preview_command = "lsd {}"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls -A"

[[session]]
name = "Projects 📂"
path = "~/workspace/github.com/ItzTas/"
startup_command = "nvim ."
