#!/usr/bin/env bash

_get_target_dir() {
    local first_sel
    first_sel="$(printf "%s" "${NEMO_SCRIPT_SELECTED_FILE_PATHS:-}" | head -n 1)"

    if [ "$first_sel" != "" ]; then
        if [ -d "$first_sel" ]; then
            echo "$first_sel"
        else
            dirname "$first_sel"
        fi
    else
        echo "$PWD"
    fi
}

_open() {
    set -euo pipefail

    target_dir=$(_get_target_dir)

    session_name="$(basename "$target_dir" | tr '.' '_')"
    session_name="$(basename "$session_name" | tr ' ' '_')"

    local tmux_cmd="tmux new-session -A -s \"$session_name\""

    ghostty --working-directory="$target_dir" -e "$tmux_cmd"
}

_open
