#!/bin/bash

trimmed_path=$(echo "$NEMO_SCRIPT_SELECTED_FILE_PATHS" | sed 's/^[ \t]*//;s/[ \t]*$//')

scrPWD="
new_ss() {
    local direc
    direc=\$(pwd)
    direc=\"\${direc##*( )}\"
    direc=\"\${direc%%*( )}\"
    if [[ -z \"\$direc\" ]]; then
        return 0
    fi

    local d
    d=\"\$(basename \"\$(pwd)\")\"
    d=\"\${d//./_}\"

    tmux new-session -d -s \"\$d\"
    while ! tmux has-session -t \"\$d\"; do
        sleep 0.01
    done

    tmux attach-session -t \"\$d\"
}

new_ss
"

scrPATH="
new_ss() {
    local d
    d=\"\$(basename \"$trimmed_path\")\"
    d=\"\${d//./_}\"

    cd \"$trimmed_path\"
    tmux new-session -d -s \"\$d\"
    while ! tmux has-session -t \"\$d\"; do
        sleep 0.01
    done

    tmux attach-session -t \"\$d\"
}

new_ss
"

if [ "$trimmed_path" != "" ]; then
    ghostty --working-directory="$(dirname "$trimmed_path")" -e "bash -c \"$scrPATH\""
else
    ghostty --working-directory="$PWD" -e "bash -c \"$scrPWD\""
fi
