exec-once = systemctl --user start gamemoded
exec-once = easyeffects --gapplication-service
exec = eww --config ~/.config/eww/binaryharbinger daemon
exec-once = sleep 30 && protonvpn-app --start-minimized
