source = ~/.config/hypr/hyprlang/hyprmonitor.conf
source = ~/.config/hypr/hyprlang/hyprenvs.conf
source = ~/.config/hypr/hyprlang/hyprservices.conf
source = ~/.config/hypr/hyprlang/hyprapps.conf
source = ~/.config/hypr/hyprlang/hyprbinds.conf
source = ~/.config/hypr/hyprlang/hyprrules.conf
source = ~/.config/hypr/hyprlang/hyprsettings.conf
source = ~/.config/hypr/hyprlang/hyprplugins.conf
