#!/bin/env zsh
# vim: filetype=zsh

lsd_widget() { lsd -F }
yazi_widget() { yazi }
fk_widget() { fk }
fe_widget() { fe }
sesh_connect_widget() { sesh_connect }
tmux_manager_widget() { tmux_manager }

zle -N lsd_widget
zle -N yazi_widget
zle -N fk_widget
zle -N fe_widget
zle -N sesh_connect_widget
zle -N tmux_manager_widget

bindkey "\eg" lsd_widget    # Alt+g
bindkey "\ey" yazi_widget   # Alt+y
bindkey "^B" fk_widget      # Ctrl+b
bindkey "^O" fe_widget      # Ctrl+o
# bindkey "\eb" pf_widget    # Alt+b (comentado)
# bindkey "^F" new_ss_widget # Ctrl+f (comentado)
# bindkey "^A" fs_widget     # Ctrl+a (comentado)

if [ -z "$TMUX" ]; then
    bindkey "^F" sesh_connect_widget
    bindkey "^G" tmux_manager_widget
fi

