#!/bin/env zsh
# vim: filetype=zsh

lsd_widget() { lsd -F }
yazi_widget() { yazi }
fk_widget() { fk }
fe_widget() { fe }
sesh_connect_widget() { sesh_connect }

zle -N lsd_widget
zle -N yazi_widget
zle -N fk_widget
zle -N fe_widget
zle -N sesh_connect_widget

bindkey "\eg" lsd_widget    # Alt+g
bindkey "\ey" yazi_widget   # Alt+y
bindkey "^B" fk_widget      # Ctrl+b
bindkey "^O" fe_widget      # Ctrl+o
# bindkey "\eb" pf_widget    # Alt+b 
# bindkey "^F" new_ss_widget # Ctrl+f 
# bindkey "^A" fs_widget     # Ctrl+a 

# Completion settings
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^Y' yank
bindkey '^D' delete-char
bindkey '^W' backward-kill-word
bindkey '^H' backward-kill-word
bindkey '\ed' kill-word
bindkey '^T' transpose-chars
bindkey '\eb' backward-word
bindkey '\ef' forward-word
bindkey '^L' clear-screen
bindkey '^K' kill-line

# Completion & history
bindkey '^I' expand-or-complete
bindkey '\e[Z' reverse-menu-complete
bindkey '\e[A' history-search-backward
bindkey '\e[B' history-search-forward

# Others
bindkey '\e.' yank-last-arg
