#!/bin/env zsh
# vim: filetype=zsh

export PATH=$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH

mkdir -p "$HOME/.zsh_completions"

autoload -U +X compinit
compinit

# Proto completions
if command -v proto >/dev/null 2>&1; then
    if [ ! -f "$HOME/.zsh_completions/proto.zsh" ]; then
        mkdir -p ~/.zsh_completions
        proto completions --shell zsh >~/.zsh_completions/proto.zsh
    fi
    source "$HOME/.zsh_completions/proto.zsh"
fi

# Bootdev completions
if command -v bootdev >/dev/null 2>&1; then
    if [ ! -f "$HOME/.zsh_completions/bootdev.zsh" ]; then
        mkdir -p ~/.zsh_completions
        bootdev completion zsh >~/.zsh_completions/bootdev.zsh
    fi
    source "$HOME/.zsh_completions/bootdev.zsh"
fi

# Eww completions
if command -v eww >/dev/null 2>&1; then
    if [ ! -f "$HOME/.zsh_completions/eww.zsh" ]; then
        mkdir -p ~/.zsh_completions
        eww shell-completions --shell zsh >"$HOME/.zsh_completions/eww.zsh"
    fi
    source "$HOME/.zsh_completions/eww.zsh"
fi

# GitBug completions
if command -v git-bug >/dev/null 2>&1; then
    if [ ! -f "$HOME/.zsh_completions/gitbug.zsh" ]; then
        mkdir -p ~/.zsh_completions
        git bug completion zsh >"$HOME/.zsh_completions/gitbug.zsh"
    fi
    source "$HOME/.zsh_completions/gitbug.zsh"
fi
