#!/usr/bin/env zsh
# vim: filetype=zsh

# zsh is kinda stupid so it needs this
export PATH=$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH

# don't put duplicate lines or lines starting with space in the history.
setopt HIST_IGNORE_ALL_DUPS  # similar to ignoreboth
setopt HIST_IGNORE_SPACE

# initial project path
export MY_PROJECT_PATH="$PWD"

# for not accidentally exiting with ctrl+d
export IGNOREEOF=999

# less
export LESS='-R'

# bat
export BAT_THEME="Catppuccin Mocha"

# browser
export BROWSER='zen-browser'

# editor
if command -v nvim >/dev/null 2>&1; then
    export EDITOR='nvim'
fi

# terminal
if command -v ghostty >/dev/null 2>&1; then
    export TERMINAL="ghostty"
elif command -v kitty >/dev/null 2>&1; then
    export TERMINAL="kitty"
fi

# colors in gcc
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# history length
export HISTSIZE=1000
export HISTFILESIZE=2000
export HISTTIMEFORMAT='%m-%d %T '

# hyprcursor
export HYPRCURSOR_THEME="Bibata-Modern-Classic"

# hyprshot
export HYPRSHOT_DIR="$HOME/Pictures/screenshots/"

# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_TEMPLATES_DIR="$HOME/Templates"
export XDG_PUBLICSHARE_DIR="$HOME/Public"
export XDG_DOCUMENTS_DIR="$HOME/Docs"
export XDG_MUSIC_DIR="$HOME/Musics"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_VIDEOS_DIR="$HOME/Videos"

# ---- PATH EXPORTS ----

export PATH="$PATH:/home/talinux/.dotnet/tools"
export ANDROID_HOME="$HOME/.AndroidS/Sdk"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH"

# go bin
if command -v go >/dev/null 2>&1; then
    export PATH="$PATH:$HOME/go/bin"
fi

# phpenv
if command -v phpenv >/dev/null 2>&1; then
    export PATH="$HOME/.phpenv/bin:$PATH"
fi

# cargo
if command -v cargo >/dev/null 2>&1; then
    export PATH="$PATH:$HOME/.cargo/env"
fi

# snap
if command -v snap >/dev/null 2>&1; then
    export PATH="$PATH:/var/lib/snapd/snap/bin"
fi
