#!/usr/bin/env zsh
# vim: filetype=zsh

zmodload zsh/complist

zstyle ':completion:*' list-colors \
    'di=38;5;189' \
    'ln=38;5;175' \
    'so=38;5;204' \
    'pi=38;5;221' \
    'ex=38;5;166' \
    'bd=38;5;248' \
    'cd=38;5;252' \
    'su=38;5;167' \
    'sg=38;5;172' \
    'tw=38;5;141' \
    'ow=38;5;145' \
    'st=38;5;175'

zstyle ':completion:*' format '%F{cyan}%d%f'
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:matches' group-name ''
zstyle ':completion:*:messages' format '%F{gray}%d%f'

zstyle ':completion:*' menu select=2

