[colors]
ansi = [
    "#424750",
    "#ffb4ab",
    "#a5c8ff",
    "#b7c7e5",
    "#ecb2fb",
    "#a5c8ff",
    "#b7c7e5",
    "#e2e2e8",
]
background = "#111317"
brights = [
    "#8c919b",
    "#ffb4ab",
    "#a5c8ff",
    "#b7c7e5",
    "#ecb2fb",
    "#a5c8ff",
    "#b7c7e5",
    "#e2e2e8",
]
compose_cursor = "#e2e2e8"
cursor_bg = "#e2e2e8"
cursor_border = "#e2e2e8"
cursor_fg = "#111317"
foreground = "#e2e2e8"
scrollbar_thumb = "#424750"
selection_bg = "#424750"
selection_fg = "#c2c6d1"
split = "#8c919b"
visual_bell = "#424750"

[colors.indexed]
16 = "#b7c7e5"
17 = "#e2e2e8"

[colors.tab_bar]
background = "#111317"
inactive_tab_edge = "#424750"

[colors.tab_bar.active_tab]
bg_color = "#a5c8ff"
fg_color = "#00315e"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#111317"
fg_color = "#e2e2e8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#111317"
fg_color = "#e2e2e8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#424750"
fg_color = "#e2e2e8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#8c919b"
fg_color = "#e2e2e8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
author = "Noctalia"
name = "Noctalia"
