[colors]
ansi = [
    "#4f434f",
    "#ffb4ab",
    "#f9acff",
    "#e6b8e6",
    "#ffb1c0",
    "#f9acff",
    "#e6b8e6",
    "#ecdfe8",
]
background = "#181118"
brights = [
    "#9c8c9a",
    "#ffb4ab",
    "#f9acff",
    "#e6b8e6",
    "#ffb1c0",
    "#f9acff",
    "#e6b8e6",
    "#ecdfe8",
]
compose_cursor = "#ecdfe8"
cursor_bg = "#ecdfe8"
cursor_border = "#ecdfe8"
cursor_fg = "#181118"
foreground = "#ecdfe8"
scrollbar_thumb = "#4f434f"
selection_bg = "#4f434f"
selection_fg = "#d3c1d0"
split = "#9c8c9a"
visual_bell = "#4f434f"

[colors.indexed]
16 = "#e6b8e6"
17 = "#ecdfe8"

[colors.tab_bar]
background = "#181118"
inactive_tab_edge = "#4f434f"

[colors.tab_bar.active_tab]
bg_color = "#f9acff"
fg_color = "#570066"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#181118"
fg_color = "#ecdfe8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#181118"
fg_color = "#ecdfe8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#4f434f"
fg_color = "#ecdfe8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#9c8c9a"
fg_color = "#ecdfe8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
author = "Noctalia"
name = "Noctalia"
