/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Generated at: 2024-10-09 09:01:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.atlassian.jira.security.JiraAuthenticationContext;
import com.atlassian.jira.util.I18nHelper;
import com.atlassian.jira.web.util.ProductVersionDataBean;
import com.atlassian.jira.web.util.ProductVersionDataBeanProvider;
import com.atlassian.webresource.api.WebResourceManager;
import com.opensymphony.util.TextUtils;
import org.apache.commons.httpclient.HttpStatus;
import com.atlassian.jira.component.ComponentAccessor;
import com.atlassian.jira.plugin.navigation.HeaderFooterRendering;
import com.atlassian.web.servlet.api.LocationUpdater;
import com.atlassian.jira.web.pagebuilder.CommonWebResourcesProvider;
import com.atlassian.jira.plugin.navigation.LfStylesService;

public final class displayError_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/includes/decorators/aui-layout/head-resources.jsp", Long.valueOf(1728464177867L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.atlassian.jira.web.util.ProductVersionDataBeanProvider");
    _jspx_imports_classes.add("com.atlassian.web.servlet.api.LocationUpdater");
    _jspx_imports_classes.add("com.atlassian.webresource.api.WebResourceManager");
    _jspx_imports_classes.add("com.opensymphony.util.TextUtils");
    _jspx_imports_classes.add("com.atlassian.jira.plugin.navigation.LfStylesService");
    _jspx_imports_classes.add("com.atlassian.jira.util.I18nHelper");
    _jspx_imports_classes.add("com.atlassian.jira.plugin.navigation.HeaderFooterRendering");
    _jspx_imports_classes.add("com.atlassian.jira.security.JiraAuthenticationContext");
    _jspx_imports_classes.add("com.atlassian.jira.component.ComponentAccessor");
    _jspx_imports_classes.add("org.apache.commons.httpclient.HttpStatus");
    _jspx_imports_classes.add("com.atlassian.jira.web.pagebuilder.CommonWebResourcesProvider");
    _jspx_imports_classes.add("com.atlassian.jira.web.util.ProductVersionDataBean");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjira_005fa11y_002dclasses_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fui_005fparam_0026_005fname;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fjira_005fa11y_002dclasses_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fui_005fparam_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fjira_005fa11y_002dclasses_005fnobody.release();
    _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.release();
    _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n\n\n\n\n\n\n\n\n");

    WebResourceManager webResourceManager = ComponentAccessor.getComponentSafely(WebResourceManager.class).get();

      out.write("\n<html>\n");

    // include the relevant contexts
    webResourceManager.requireResourcesForContext("atl.general");
    webResourceManager.requireResourcesForContext("jira.general");
    webResourceManager.requireResourcesForContext("atl.global");
    webResourceManager.requireResourcesForContext("jira.global");

    // figure out the status code
    Integer statusCode = (Integer) request.getAttribute("javax.servlet.error.status_code");
    String statusText = HttpStatus.getStatusText(statusCode);
    String errorMessage = (String) request.getAttribute("javax.servlet.error.message");
    if (errorMessage == null) {
        errorMessage = "";
    }

    I18nHelper i18nBean = ComponentAccessor.getComponent(JiraAuthenticationContext.class).getI18nHelper();
    ProductVersionDataBean dataBean = ComponentAccessor.getComponent(ProductVersionDataBeanProvider.class).get();

      out.write("\n<head>\n    <title>");
      out.print(TextUtils.htmlEncode(statusText));
      out.write(' ');
      out.write('(');
      out.print(statusCode);
      out.write(")</title>\n    ");
      out.write("\n\n\n\n\n");
      out.print(ComponentAccessor.getComponent(LfStylesService.class).prepareLookAndFeelColorsCss());
      out.write("\n\n<script>window.contextPath = '");
      out.print(request.getContextPath());
      out.write("';</script>\n");

    final LocationUpdater locationUpdater = ComponentAccessor.getOSGiComponentInstanceOfType(LocationUpdater.class);
    locationUpdater.updateLocation(out);

    CommonWebResourcesProvider commonWebResourcesProvider = ComponentAccessor.getComponent(CommonWebResourcesProvider.class);
    commonWebResourcesProvider.requireCommonWebResources();
    commonWebResourcesProvider.drainIncludedWebResources(out);

    HeaderFooterRendering headerAndFooter = ComponentAccessor.getComponent(HeaderFooterRendering.class);
    headerAndFooter.includeWebPanels(out, "atl.header.after.scripts");

      out.write('\n');
      out.write("\n    ");
      out.print( dataBean.getMetaTags() );
      out.write("\n</head>\n<body id=\"jira\" class=\"aui-layout aui-style-default page-type-message ");
      if (_jspx_meth_jira_005fa11y_002dclasses_005f0(_jspx_page_context))
        return;
      out.write('"');
      out.write(' ');
      out.print( dataBean.getBodyHtmlAttributes() );
      out.write(' ');
      out.write('>');
      out.write('\n');
      out.write("\n<!-- HTTPError");
      out.print(statusCode);
      out.write(" -->\n    ");
      //  ui:soy
      com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f0 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
      boolean _jspx_th_ui_005fsoy_005f0_reused = false;
      try {
        _jspx_th_ui_005fsoy_005f0.setPageContext(_jspx_page_context);
        _jspx_th_ui_005fsoy_005f0.setParent(null);
        // /displayError.jsp(41,4) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ui_005fsoy_005f0.setModuleKey("'com.atlassian.auiplugin:soy'");
        // /displayError.jsp(41,4) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ui_005fsoy_005f0.setTemplate("'aui.page.pagePanel'");
        int _jspx_eval_ui_005fsoy_005f0 = _jspx_th_ui_005fsoy_005f0.doStartTag();
        if (_jspx_eval_ui_005fsoy_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_ui_005fsoy_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fsoy_005f0);
          }
          do {
            out.write("\n        ");
            //  ui:param
            webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f0 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
            boolean _jspx_th_ui_005fparam_005f0_reused = false;
            try {
              _jspx_th_ui_005fparam_005f0.setPageContext(_jspx_page_context);
              _jspx_th_ui_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f0);
              // /displayError.jsp(42,8) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_ui_005fparam_005f0.setName("'content'");
              int _jspx_eval_ui_005fparam_005f0 = _jspx_th_ui_005fparam_005f0.doStartTag();
              if (_jspx_eval_ui_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                if (_jspx_eval_ui_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fparam_005f0);
                }
                do {
                  out.write("\n            ");
                  //  ui:soy
                  com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f1 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
                  boolean _jspx_th_ui_005fsoy_005f1_reused = false;
                  try {
                    _jspx_th_ui_005fsoy_005f1.setPageContext(_jspx_page_context);
                    _jspx_th_ui_005fsoy_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f0);
                    // /displayError.jsp(43,12) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_ui_005fsoy_005f1.setModuleKey("'com.atlassian.auiplugin:soy'");
                    // /displayError.jsp(43,12) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_ui_005fsoy_005f1.setTemplate("'aui.page.pagePanelContent'");
                    int _jspx_eval_ui_005fsoy_005f1 = _jspx_th_ui_005fsoy_005f1.doStartTag();
                    if (_jspx_eval_ui_005fsoy_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                      if (_jspx_eval_ui_005fsoy_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                        out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fsoy_005f1);
                      }
                      do {
                        out.write("\n                ");
                        //  ui:param
                        webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f1 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
                        boolean _jspx_th_ui_005fparam_005f1_reused = false;
                        try {
                          _jspx_th_ui_005fparam_005f1.setPageContext(_jspx_page_context);
                          _jspx_th_ui_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f1);
                          // /displayError.jsp(44,16) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_ui_005fparam_005f1.setName("'content'");
                          int _jspx_eval_ui_005fparam_005f1 = _jspx_th_ui_005fparam_005f1.doStartTag();
                          if (_jspx_eval_ui_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            if (_jspx_eval_ui_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fparam_005f1);
                            }
                            do {
                              out.write("\n                    ");
                              //  ui:soy
                              com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f2 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
                              boolean _jspx_th_ui_005fsoy_005f2_reused = false;
                              try {
                              _jspx_th_ui_005fsoy_005f2.setPageContext(_jspx_page_context);
                              _jspx_th_ui_005fsoy_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f1);
                              // /displayError.jsp(45,20) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_ui_005fsoy_005f2.setModuleKey("'com.atlassian.auiplugin:soy'");
                              // /displayError.jsp(45,20) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_ui_005fsoy_005f2.setTemplate("'aui.page.pageHeader'");
                              int _jspx_eval_ui_005fsoy_005f2 = _jspx_th_ui_005fsoy_005f2.doStartTag();
                              if (_jspx_eval_ui_005fsoy_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                              if (_jspx_eval_ui_005fsoy_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fsoy_005f2);
                              }
                              do {
                              out.write("\n                        ");
                              //  ui:param
                              webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f2 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
                              boolean _jspx_th_ui_005fparam_005f2_reused = false;
                              try {
                              _jspx_th_ui_005fparam_005f2.setPageContext(_jspx_page_context);
                              _jspx_th_ui_005fparam_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f2);
                              // /displayError.jsp(46,24) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_ui_005fparam_005f2.setName("'content'");
                              int _jspx_eval_ui_005fparam_005f2 = _jspx_th_ui_005fparam_005f2.doStartTag();
                              if (_jspx_eval_ui_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                              if (_jspx_eval_ui_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fparam_005f2);
                              }
                              do {
                              out.write("\n                            ");
                              //  ui:soy
                              com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f3 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
                              boolean _jspx_th_ui_005fsoy_005f3_reused = false;
                              try {
                              _jspx_th_ui_005fsoy_005f3.setPageContext(_jspx_page_context);
                              _jspx_th_ui_005fsoy_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f2);
                              // /displayError.jsp(47,28) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_ui_005fsoy_005f3.setModuleKey("'com.atlassian.auiplugin:soy'");
                              // /displayError.jsp(47,28) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_ui_005fsoy_005f3.setTemplate("'aui.page.pageHeaderMain'");
                              int _jspx_eval_ui_005fsoy_005f3 = _jspx_th_ui_005fsoy_005f3.doStartTag();
                              if (_jspx_eval_ui_005fsoy_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                              if (_jspx_eval_ui_005fsoy_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fsoy_005f3);
                              }
                              do {
                              out.write("\n                                ");
                              //  ui:param
                              webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f3 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
                              boolean _jspx_th_ui_005fparam_005f3_reused = false;
                              try {
                              _jspx_th_ui_005fparam_005f3.setPageContext(_jspx_page_context);
                              _jspx_th_ui_005fparam_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f3);
                              // /displayError.jsp(48,32) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_ui_005fparam_005f3.setName("'content'");
                              int _jspx_eval_ui_005fparam_005f3 = _jspx_th_ui_005fparam_005f3.doStartTag();
                              if (_jspx_eval_ui_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                              if (_jspx_eval_ui_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fparam_005f3);
                              }
                              do {
                              out.write("\n                                    <h1>");
                              out.print(TextUtils.htmlEncode(statusText));
                              out.write(' ');
                              out.write('(');
                              out.print(statusCode);
                              out.write(")</h1>\n                                ");
                              int evalDoAfterBody = _jspx_th_ui_005fparam_005f3.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                              } while (true);
                              if (_jspx_eval_ui_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                              }
                              }
                              if (_jspx_th_ui_005fparam_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                              return;
                              }
                              _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f3);
                              _jspx_th_ui_005fparam_005f3_reused = true;
                              } finally {
                              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f3, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f3_reused);
                              }
                              out.write("\n                            ");
                              int evalDoAfterBody = _jspx_th_ui_005fsoy_005f3.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                              } while (true);
                              if (_jspx_eval_ui_005fsoy_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                              }
                              }
                              if (_jspx_th_ui_005fsoy_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                              return;
                              }
                              _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f3);
                              _jspx_th_ui_005fsoy_005f3_reused = true;
                              } finally {
                              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fsoy_005f3, _jsp_getInstanceManager(), _jspx_th_ui_005fsoy_005f3_reused);
                              }
                              out.write("\n                        ");
                              int evalDoAfterBody = _jspx_th_ui_005fparam_005f2.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                              } while (true);
                              if (_jspx_eval_ui_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                              }
                              }
                              if (_jspx_th_ui_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                              return;
                              }
                              _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f2);
                              _jspx_th_ui_005fparam_005f2_reused = true;
                              } finally {
                              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f2, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f2_reused);
                              }
                              out.write("\n                    ");
                              int evalDoAfterBody = _jspx_th_ui_005fsoy_005f2.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                              } while (true);
                              if (_jspx_eval_ui_005fsoy_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                              }
                              }
                              if (_jspx_th_ui_005fsoy_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                              return;
                              }
                              _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f2);
                              _jspx_th_ui_005fsoy_005f2_reused = true;
                              } finally {
                              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fsoy_005f2, _jsp_getInstanceManager(), _jspx_th_ui_005fsoy_005f2_reused);
                              }
                              out.write("\n                    ");
                              //  ui:soy
                              com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f4 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
                              boolean _jspx_th_ui_005fsoy_005f4_reused = false;
                              try {
                              _jspx_th_ui_005fsoy_005f4.setPageContext(_jspx_page_context);
                              _jspx_th_ui_005fsoy_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f1);
                              // /displayError.jsp(54,20) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_ui_005fsoy_005f4.setModuleKey("'com.atlassian.auiplugin:soy'");
                              // /displayError.jsp(54,20) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_ui_005fsoy_005f4.setTemplate("'aui.message.warning'");
                              int _jspx_eval_ui_005fsoy_005f4 = _jspx_th_ui_005fsoy_005f4.doStartTag();
                              if (_jspx_eval_ui_005fsoy_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                              if (_jspx_eval_ui_005fsoy_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fsoy_005f4);
                              }
                              do {
                              out.write("\n                        ");
                              //  ui:param
                              webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f4 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
                              boolean _jspx_th_ui_005fparam_005f4_reused = false;
                              try {
                              _jspx_th_ui_005fparam_005f4.setPageContext(_jspx_page_context);
                              _jspx_th_ui_005fparam_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f4);
                              // /displayError.jsp(55,24) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_ui_005fparam_005f4.setName("'content'");
                              int _jspx_eval_ui_005fparam_005f4 = _jspx_th_ui_005fparam_005f4.doStartTag();
                              if (_jspx_eval_ui_005fparam_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                              if (_jspx_eval_ui_005fparam_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fparam_005f4);
                              }
                              do {
                              out.write("\n                            <p>");
                              out.print(i18nBean.getText("http.generic.error.message", TextUtils.htmlEncode("\"" + statusCode + " - " + statusText + "\"")));
                              out.write("</p>\n                            <p>");
                              out.print( TextUtils.htmlEncode(errorMessage) );
                              out.write("</p>\n                            <p><a href=\"");
                              out.print(request.getContextPath());
                              out.write("/secure/MyJiraHome.jspa\">");
                              out.print(TextUtils.htmlEncode(i18nBean.getText("admin.keyboard.shortcut.goto.homr.desc")));
                              out.write("</a></p>\n                        ");
                              int evalDoAfterBody = _jspx_th_ui_005fparam_005f4.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                              } while (true);
                              if (_jspx_eval_ui_005fparam_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                              }
                              }
                              if (_jspx_th_ui_005fparam_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                              return;
                              }
                              _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f4);
                              _jspx_th_ui_005fparam_005f4_reused = true;
                              } finally {
                              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f4, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f4_reused);
                              }
                              out.write("\n                    ");
                              int evalDoAfterBody = _jspx_th_ui_005fsoy_005f4.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                              } while (true);
                              if (_jspx_eval_ui_005fsoy_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                              }
                              }
                              if (_jspx_th_ui_005fsoy_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                              return;
                              }
                              _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f4);
                              _jspx_th_ui_005fsoy_005f4_reused = true;
                              } finally {
                              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fsoy_005f4, _jsp_getInstanceManager(), _jspx_th_ui_005fsoy_005f4_reused);
                              }
                              out.write("\n                ");
                              int evalDoAfterBody = _jspx_th_ui_005fparam_005f1.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                            if (_jspx_eval_ui_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                            }
                          }
                          if (_jspx_th_ui_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                          _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f1);
                          _jspx_th_ui_005fparam_005f1_reused = true;
                        } finally {
                          org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f1, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f1_reused);
                        }
                        out.write("\n            ");
                        int evalDoAfterBody = _jspx_th_ui_005fsoy_005f1.doAfterBody();
                        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                          break;
                      } while (true);
                      if (_jspx_eval_ui_005fsoy_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                        out = _jspx_page_context.popBody();
                      }
                    }
                    if (_jspx_th_ui_005fsoy_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f1);
                    _jspx_th_ui_005fsoy_005f1_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fsoy_005f1, _jsp_getInstanceManager(), _jspx_th_ui_005fsoy_005f1_reused);
                  }
                  out.write("\n        ");
                  int evalDoAfterBody = _jspx_th_ui_005fparam_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
                if (_jspx_eval_ui_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.popBody();
                }
              }
              if (_jspx_th_ui_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f0);
              _jspx_th_ui_005fparam_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f0_reused);
            }
            out.write("\n    ");
            int evalDoAfterBody = _jspx_th_ui_005fsoy_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_ui_005fsoy_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_ui_005fsoy_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f0);
        _jspx_th_ui_005fsoy_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fsoy_005f0, _jsp_getInstanceManager(), _jspx_th_ui_005fsoy_005f0_reused);
      }
      out.write("\n</body>\n</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_jira_005fa11y_002dclasses_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jira:a11y-classes
    com.atlassian.jira.web.tags.A11yClassesTag _jspx_th_jira_005fa11y_002dclasses_005f0 = (com.atlassian.jira.web.tags.A11yClassesTag) _005fjspx_005ftagPool_005fjira_005fa11y_002dclasses_005fnobody.get(com.atlassian.jira.web.tags.A11yClassesTag.class);
    boolean _jspx_th_jira_005fa11y_002dclasses_005f0_reused = false;
    try {
      _jspx_th_jira_005fa11y_002dclasses_005f0.setPageContext(_jspx_page_context);
      _jspx_th_jira_005fa11y_002dclasses_005f0.setParent(null);
      int _jspx_eval_jira_005fa11y_002dclasses_005f0 = _jspx_th_jira_005fa11y_002dclasses_005f0.doStartTag();
      if (_jspx_th_jira_005fa11y_002dclasses_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fjira_005fa11y_002dclasses_005fnobody.reuse(_jspx_th_jira_005fa11y_002dclasses_005f0);
      _jspx_th_jira_005fa11y_002dclasses_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_jira_005fa11y_002dclasses_005f0, _jsp_getInstanceManager(), _jspx_th_jira_005fa11y_002dclasses_005f0_reused);
    }
    return false;
  }
}
