

# cursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,24

# hyprland envs
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland



# proton
env = PROTON_ENABLE_WAYLAND,1
env = PROTON_ENABLE_HDR,1

# system theme
env = QT_QPA_PLATFORMTHEME,qt6ct
env = GTK_THEME,catppuccin-mocha-lavender-standard+default

# zsh home
env = ZDOTDIR,$HOME/.config/zsh
