/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Generated at: 2024-10-09 09:01:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package jsp.includes.panels;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class permissionslist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tld/sitemesh-page.tld", Long.valueOf(1728464177835L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005fcomponent_0026_005ftemplate_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005faui_005fcomponent_0026_005ftheme_005ftemplate;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005faui_005fparam_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fui_005fselect_0026_005fname_005flistValue_005flistKey_005flist_005flabel;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fui_005fparam_0026_005fvalue_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fui_005fcomponent_0026_005fvalue_005ftheme_005ftemplate_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fww_005fcomponent_0026_005ftemplate_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005faui_005fcomponent_0026_005ftheme_005ftemplate = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005faui_005fparam_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fui_005fselect_0026_005fname_005flistValue_005flistKey_005flist_005flabel = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fui_005fparam_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fui_005fcomponent_0026_005fvalue_005ftheme_005ftemplate_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fww_005fcomponent_0026_005ftemplate_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005faui_005fcomponent_0026_005ftheme_005ftemplate.release();
    _005fjspx_005ftagPool_005faui_005fparam_0026_005fname.release();
    _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname.release();
    _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.release();
    _005fjspx_005ftagPool_005fui_005fselect_0026_005fname_005flistValue_005flistKey_005flist_005flabel.release();
    _005fjspx_005ftagPool_005fui_005fparam_0026_005fvalue_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue.release();
    _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fui_005fcomponent_0026_005fvalue_005ftheme_005ftemplate_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n\n\n\n<h3>\n    ");
      if (_jspx_meth_ww_005fcomponent_005f0(_jspx_page_context))
        return;
      out.write("\n    ");
      if (_jspx_meth_ww_005ftext_005f0(_jspx_page_context))
        return;
      out.write("\n</h3>\n\n");
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "permission/list_table.jsp", out, false);
      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_aui_005fcomponent_005f0(_jspx_page_context))
        return;
      out.write("\n<div id=\"default-groups-warning\" class=\"aui-message aui-message-warning hidden\">\n    <p class=\"title\">\n        ");
      if (_jspx_meth_ww_005ftext_005f6(_jspx_page_context))
        return;
      out.write("\n    </p>\n    <p id=\"default-group-warning-message\">\n    </p>\n</div>\n<div id=\"sharing-with-anyone-warning\" class=\"aui-message aui-message-warning hidden\">\n    <p class=\"title\">\n        ");
      if (_jspx_meth_ww_005ftext_005f7(_jspx_page_context))
        return;
      out.write("\n    </p>\n    <p>\n        ");
      if (_jspx_meth_ww_005ftext_005f8(_jspx_page_context))
        return;
      out.write("\n    </p>\n</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_ww_005fcomponent_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:component
    webwork.view.taglib.ui.ComponentTag _jspx_th_ww_005fcomponent_005f0 = (webwork.view.taglib.ui.ComponentTag) _005fjspx_005ftagPool_005fww_005fcomponent_0026_005ftemplate_005fname_005fnobody.get(webwork.view.taglib.ui.ComponentTag.class);
    boolean _jspx_th_ww_005fcomponent_005f0_reused = false;
    try {
      _jspx_th_ww_005fcomponent_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fcomponent_005f0.setParent(null);
      // /includes/panels/permissionslist.jsp(7,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fcomponent_005f0.setName("'permissions'");
      // /includes/panels/permissionslist.jsp(7,4) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fcomponent_005f0.setTemplate("help.jsp");
      int _jspx_eval_ww_005fcomponent_005f0 = _jspx_th_ww_005fcomponent_005f0.doStartTag();
      if (_jspx_th_ww_005fcomponent_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fcomponent_0026_005ftemplate_005fname_005fnobody.reuse(_jspx_th_ww_005fcomponent_005f0);
      _jspx_th_ww_005fcomponent_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fcomponent_005f0, _jsp_getInstanceManager(), _jspx_th_ww_005fcomponent_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f0 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f0_reused = false;
    try {
      _jspx_th_ww_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f0.setParent(null);
      // /includes/panels/permissionslist.jsp(8,4) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f0.setName("'admin.globalpermissions.jira.permissions'");
      int _jspx_eval_ww_005ftext_005f0 = _jspx_th_ww_005ftext_005f0.doStartTag();
      if (_jspx_th_ww_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f0);
      _jspx_th_ww_005ftext_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f0, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_aui_005fcomponent_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  aui:component
    webwork.view.taglib.ui.ComponentTag _jspx_th_aui_005fcomponent_005f0 = (webwork.view.taglib.ui.ComponentTag) _005fjspx_005ftagPool_005faui_005fcomponent_0026_005ftheme_005ftemplate.get(webwork.view.taglib.ui.ComponentTag.class);
    boolean _jspx_th_aui_005fcomponent_005f0_reused = false;
    try {
      _jspx_th_aui_005fcomponent_005f0.setPageContext(_jspx_page_context);
      _jspx_th_aui_005fcomponent_005f0.setParent(null);
      // /includes/panels/permissionslist.jsp(15,0) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fcomponent_005f0.setTemplate("module.jsp");
      // /includes/panels/permissionslist.jsp(15,0) name = theme type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fcomponent_005f0.setTheme("'aui'");
      int _jspx_eval_aui_005fcomponent_005f0 = _jspx_th_aui_005fcomponent_005f0.doStartTag();
      if (_jspx_eval_aui_005fcomponent_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_aui_005fcomponent_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_aui_005fcomponent_005f0);
        }
        do {
          out.write("\n    ");
          if (_jspx_meth_aui_005fparam_005f0(_jspx_th_aui_005fcomponent_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          int evalDoAfterBody = _jspx_th_aui_005fcomponent_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_aui_005fcomponent_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_aui_005fcomponent_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005faui_005fcomponent_0026_005ftheme_005ftemplate.reuse(_jspx_th_aui_005fcomponent_005f0);
      _jspx_th_aui_005fcomponent_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005fcomponent_005f0, _jsp_getInstanceManager(), _jspx_th_aui_005fcomponent_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_aui_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_aui_005fcomponent_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  aui:param
    webwork.view.taglib.ParamTag _jspx_th_aui_005fparam_005f0 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005faui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
    boolean _jspx_th_aui_005fparam_005f0_reused = false;
    try {
      _jspx_th_aui_005fparam_005f0.setPageContext(_jspx_page_context);
      _jspx_th_aui_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fcomponent_005f0);
      // /includes/panels/permissionslist.jsp(16,4) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fparam_005f0.setName("'contentHtml'");
      int _jspx_eval_aui_005fparam_005f0 = _jspx_th_aui_005fparam_005f0.doStartTag();
      if (_jspx_eval_aui_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_aui_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_aui_005fparam_005f0);
        }
        do {
          out.write("\n        ");
          if (_jspx_meth_page_005fapplyDecorator_005f0(_jspx_th_aui_005fparam_005f0, _jspx_page_context))
            return true;
          out.write("\n    ");
          int evalDoAfterBody = _jspx_th_aui_005fparam_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_aui_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_aui_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005faui_005fparam_0026_005fname.reuse(_jspx_th_aui_005fparam_005f0);
      _jspx_th_aui_005fparam_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_aui_005fparam_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_page_005fapplyDecorator_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_aui_005fparam_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:applyDecorator
    com.atlassian.jira.web.tags.JiraApplyDecoratorTag _jspx_th_page_005fapplyDecorator_005f0 = (com.atlassian.jira.web.tags.JiraApplyDecoratorTag) _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname.get(com.atlassian.jira.web.tags.JiraApplyDecoratorTag.class);
    boolean _jspx_th_page_005fapplyDecorator_005f0_reused = false;
    try {
      _jspx_th_page_005fapplyDecorator_005f0.setPageContext(_jspx_page_context);
      _jspx_th_page_005fapplyDecorator_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fparam_005f0);
      // /includes/panels/permissionslist.jsp(17,8) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_page_005fapplyDecorator_005f0.setName("jiraform");
      int _jspx_eval_page_005fapplyDecorator_005f0 = _jspx_th_page_005fapplyDecorator_005f0.doStartTag();
      if (_jspx_eval_page_005fapplyDecorator_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_page_005fapplyDecorator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_page_005fapplyDecorator_005f0);
        }
        do {
          out.write("\n            ");
          if (_jspx_meth_page_005fparam_005f0(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return true;
          out.write("\n            ");
          if (_jspx_meth_page_005fparam_005f1(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return true;
          out.write("\n            ");
          if (_jspx_meth_page_005fparam_005f2(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return true;
          out.write("\n            ");
          if (_jspx_meth_page_005fparam_005f3(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return true;
          out.write("\n            ");
          if (_jspx_meth_page_005fparam_005f4(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return true;
          out.write("\n            ");
          if (_jspx_meth_page_005fparam_005f5(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return true;
          out.write("\n            ");
          out.write("\n\n            ");
          if (_jspx_meth_ui_005fselect_005f0(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return true;
          out.write("\n            ");
          if (_jspx_meth_ww_005fproperty_005f0(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return true;
          out.write("\n            <tr>\n                <td class=\"fieldLabelArea");
          if (_jspx_meth_ww_005fif_005f1(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return true;
          out.write("\">\n                    ");
          if (_jspx_meth_ww_005ftext_005f3(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return true;
          out.write("\n                </td>\n                <td id=\"group-single-selector-parent\" class=\"fieldValueArea");
          if (_jspx_meth_ww_005fif_005f2(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return true;
          out.write("\">\n                    <select name=\"groupName\" class=\"js-default-single-group-picker\" id=\"groupName_select\">\n                        <option disabled selected hidden>");
          if (_jspx_meth_ww_005ftext_005f4(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return true;
          out.write("</option>\n                        <option data-empty value=\"\">");
          if (_jspx_meth_ww_005ftext_005f5(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return true;
          out.write("</option>\n                    </select>\n                </td>\n            </tr>\n            ");
          if (_jspx_meth_ui_005fcomponent_005f0(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return true;
          out.write("\n        ");
          int evalDoAfterBody = _jspx_th_page_005fapplyDecorator_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_page_005fapplyDecorator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_page_005fapplyDecorator_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname.reuse(_jspx_th_page_005fapplyDecorator_005f0);
      _jspx_th_page_005fapplyDecorator_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_page_005fapplyDecorator_005f0, _jsp_getInstanceManager(), _jspx_th_page_005fapplyDecorator_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_page_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:param
    com.opensymphony.module.sitemesh.taglib.page.ParamTag _jspx_th_page_005fparam_005f0 = (com.opensymphony.module.sitemesh.taglib.page.ParamTag) _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.get(com.opensymphony.module.sitemesh.taglib.page.ParamTag.class);
    boolean _jspx_th_page_005fparam_005f0_reused = false;
    try {
      _jspx_th_page_005fparam_005f0.setPageContext(_jspx_page_context);
      _jspx_th_page_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /includes/panels/permissionslist.jsp(18,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_page_005fparam_005f0.setName("action");
      int _jspx_eval_page_005fparam_005f0 = _jspx_th_page_005fparam_005f0.doStartTag();
      if (_jspx_eval_page_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_page_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_page_005fparam_005f0);
        }
        do {
          out.write("GlobalPermissions.jspa");
          int evalDoAfterBody = _jspx_th_page_005fparam_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_page_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_page_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.reuse(_jspx_th_page_005fparam_005f0);
      _jspx_th_page_005fparam_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_page_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_page_005fparam_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_page_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:param
    com.opensymphony.module.sitemesh.taglib.page.ParamTag _jspx_th_page_005fparam_005f1 = (com.opensymphony.module.sitemesh.taglib.page.ParamTag) _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.get(com.opensymphony.module.sitemesh.taglib.page.ParamTag.class);
    boolean _jspx_th_page_005fparam_005f1_reused = false;
    try {
      _jspx_th_page_005fparam_005f1.setPageContext(_jspx_page_context);
      _jspx_th_page_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /includes/panels/permissionslist.jsp(19,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_page_005fparam_005f1.setName("submitId");
      int _jspx_eval_page_005fparam_005f1 = _jspx_th_page_005fparam_005f1.doStartTag();
      if (_jspx_eval_page_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_page_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_page_005fparam_005f1);
        }
        do {
          out.write("addpermission_submit");
          int evalDoAfterBody = _jspx_th_page_005fparam_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_page_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_page_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.reuse(_jspx_th_page_005fparam_005f1);
      _jspx_th_page_005fparam_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_page_005fparam_005f1, _jsp_getInstanceManager(), _jspx_th_page_005fparam_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_page_005fparam_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:param
    com.opensymphony.module.sitemesh.taglib.page.ParamTag _jspx_th_page_005fparam_005f2 = (com.opensymphony.module.sitemesh.taglib.page.ParamTag) _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.get(com.opensymphony.module.sitemesh.taglib.page.ParamTag.class);
    boolean _jspx_th_page_005fparam_005f2_reused = false;
    try {
      _jspx_th_page_005fparam_005f2.setPageContext(_jspx_page_context);
      _jspx_th_page_005fparam_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /includes/panels/permissionslist.jsp(20,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_page_005fparam_005f2.setName("submitName");
      int _jspx_eval_page_005fparam_005f2 = _jspx_th_page_005fparam_005f2.doStartTag();
      if (_jspx_eval_page_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_page_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_page_005fparam_005f2);
        }
        do {
          if (_jspx_meth_ww_005ftext_005f1(_jspx_th_page_005fparam_005f2, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_page_005fparam_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_page_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_page_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.reuse(_jspx_th_page_005fparam_005f2);
      _jspx_th_page_005fparam_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_page_005fparam_005f2, _jsp_getInstanceManager(), _jspx_th_page_005fparam_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fparam_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f1 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f1_reused = false;
    try {
      _jspx_th_ww_005ftext_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fparam_005f2);
      // /includes/panels/permissionslist.jsp(20,42) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f1.setName("'common.forms.add'");
      int _jspx_eval_ww_005ftext_005f1 = _jspx_th_ww_005ftext_005f1.doStartTag();
      if (_jspx_th_ww_005ftext_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f1);
      _jspx_th_ww_005ftext_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f1, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_page_005fparam_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:param
    com.opensymphony.module.sitemesh.taglib.page.ParamTag _jspx_th_page_005fparam_005f3 = (com.opensymphony.module.sitemesh.taglib.page.ParamTag) _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.get(com.opensymphony.module.sitemesh.taglib.page.ParamTag.class);
    boolean _jspx_th_page_005fparam_005f3_reused = false;
    try {
      _jspx_th_page_005fparam_005f3.setPageContext(_jspx_page_context);
      _jspx_th_page_005fparam_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /includes/panels/permissionslist.jsp(21,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_page_005fparam_005f3.setName("width");
      int _jspx_eval_page_005fparam_005f3 = _jspx_th_page_005fparam_005f3.doStartTag();
      if (_jspx_eval_page_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_page_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_page_005fparam_005f3);
        }
        do {
          out.write("100%");
          int evalDoAfterBody = _jspx_th_page_005fparam_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_page_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_page_005fparam_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.reuse(_jspx_th_page_005fparam_005f3);
      _jspx_th_page_005fparam_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_page_005fparam_005f3, _jsp_getInstanceManager(), _jspx_th_page_005fparam_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_page_005fparam_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:param
    com.opensymphony.module.sitemesh.taglib.page.ParamTag _jspx_th_page_005fparam_005f4 = (com.opensymphony.module.sitemesh.taglib.page.ParamTag) _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.get(com.opensymphony.module.sitemesh.taglib.page.ParamTag.class);
    boolean _jspx_th_page_005fparam_005f4_reused = false;
    try {
      _jspx_th_page_005fparam_005f4.setPageContext(_jspx_page_context);
      _jspx_th_page_005fparam_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /includes/panels/permissionslist.jsp(22,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_page_005fparam_005f4.setName("title");
      int _jspx_eval_page_005fparam_005f4 = _jspx_th_page_005fparam_005f4.doStartTag();
      if (_jspx_eval_page_005fparam_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_page_005fparam_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_page_005fparam_005f4);
        }
        do {
          if (_jspx_meth_ww_005ftext_005f2(_jspx_th_page_005fparam_005f4, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_page_005fparam_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_page_005fparam_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_page_005fparam_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.reuse(_jspx_th_page_005fparam_005f4);
      _jspx_th_page_005fparam_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_page_005fparam_005f4, _jsp_getInstanceManager(), _jspx_th_page_005fparam_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fparam_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f2 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f2_reused = false;
    try {
      _jspx_th_ww_005ftext_005f2.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fparam_005f4);
      // /includes/panels/permissionslist.jsp(22,37) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f2.setName("'admin.globalpermissions.add.permission'");
      int _jspx_eval_ww_005ftext_005f2 = _jspx_th_ww_005ftext_005f2.doStartTag();
      if (_jspx_th_ww_005ftext_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f2);
      _jspx_th_ww_005ftext_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f2, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_page_005fparam_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:param
    com.opensymphony.module.sitemesh.taglib.page.ParamTag _jspx_th_page_005fparam_005f5 = (com.opensymphony.module.sitemesh.taglib.page.ParamTag) _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.get(com.opensymphony.module.sitemesh.taglib.page.ParamTag.class);
    boolean _jspx_th_page_005fparam_005f5_reused = false;
    try {
      _jspx_th_page_005fparam_005f5.setPageContext(_jspx_page_context);
      _jspx_th_page_005fparam_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /includes/panels/permissionslist.jsp(23,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_page_005fparam_005f5.setName("autoSelectFirst");
      int _jspx_eval_page_005fparam_005f5 = _jspx_th_page_005fparam_005f5.doStartTag();
      if (_jspx_eval_page_005fparam_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_page_005fparam_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_page_005fparam_005f5);
        }
        do {
          out.write("false");
          int evalDoAfterBody = _jspx_th_page_005fparam_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_page_005fparam_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_page_005fparam_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.reuse(_jspx_th_page_005fparam_005f5);
      _jspx_th_page_005fparam_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_page_005fparam_005f5, _jsp_getInstanceManager(), _jspx_th_page_005fparam_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fselect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:select
    webwork.view.taglib.ui.SelectTag _jspx_th_ui_005fselect_005f0 = (webwork.view.taglib.ui.SelectTag) _005fjspx_005ftagPool_005fui_005fselect_0026_005fname_005flistValue_005flistKey_005flist_005flabel.get(webwork.view.taglib.ui.SelectTag.class);
    boolean _jspx_th_ui_005fselect_005f0_reused = false;
    try {
      _jspx_th_ui_005fselect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /includes/panels/permissionslist.jsp(26,12) name = label type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fselect_005f0.setLabel("text('admin.common.words.permission')");
      // /includes/panels/permissionslist.jsp(26,12) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fselect_005f0.setName("'globalPermType'");
      // /includes/panels/permissionslist.jsp(26,12) name = list type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fselect_005f0.setList("managablePermissions");
      // /includes/panels/permissionslist.jsp(26,12) name = listKey type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fselect_005f0.setListKey("'key'");
      // /includes/panels/permissionslist.jsp(26,12) name = listValue type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fselect_005f0.setListValue("'text(value)'");
      int _jspx_eval_ui_005fselect_005f0 = _jspx_th_ui_005fselect_005f0.doStartTag();
      if (_jspx_eval_ui_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ui_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ui_005fselect_005f0);
        }
        do {
          out.write("\n                ");
          if (_jspx_meth_ui_005fparam_005f0(_jspx_th_ui_005fselect_005f0, _jspx_page_context))
            return true;
          out.write("\n                ");
          if (_jspx_meth_ui_005fparam_005f1(_jspx_th_ui_005fselect_005f0, _jspx_page_context))
            return true;
          out.write("\n            ");
          int evalDoAfterBody = _jspx_th_ui_005fselect_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ui_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ui_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fselect_0026_005fname_005flistValue_005flistKey_005flist_005flabel.reuse(_jspx_th_ui_005fselect_005f0);
      _jspx_th_ui_005fselect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fselect_005f0, _jsp_getInstanceManager(), _jspx_th_ui_005fselect_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fselect_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:param
    webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f0 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fvalue_005fname_005fnobody.get(webwork.view.taglib.ParamTag.class);
    boolean _jspx_th_ui_005fparam_005f0_reused = false;
    try {
      _jspx_th_ui_005fparam_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fselect_005f0);
      // /includes/panels/permissionslist.jsp(28,16) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fparam_005f0.setName("'headerrow'");
      // /includes/panels/permissionslist.jsp(28,16) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fparam_005f0.setValue("text('admin.globalpermissions.please.select.a.permission')");
      int _jspx_eval_ui_005fparam_005f0 = _jspx_th_ui_005fparam_005f0.doStartTag();
      if (_jspx_th_ui_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_ui_005fparam_005f0);
      _jspx_th_ui_005fparam_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_ui_005fselect_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:param
    webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f1 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fvalue_005fname_005fnobody.get(webwork.view.taglib.ParamTag.class);
    boolean _jspx_th_ui_005fparam_005f1_reused = false;
    try {
      _jspx_th_ui_005fparam_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fselect_005f0);
      // /includes/panels/permissionslist.jsp(29,16) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fparam_005f1.setName("'headervalue'");
      // /includes/panels/permissionslist.jsp(29,16) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fparam_005f1.setValue("''");
      int _jspx_eval_ui_005fparam_005f1 = _jspx_th_ui_005fparam_005f1.doStartTag();
      if (_jspx_th_ui_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_ui_005fparam_005f1);
      _jspx_th_ui_005fparam_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fparam_005f1, _jsp_getInstanceManager(), _jspx_th_ui_005fparam_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f0 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f0_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /includes/panels/permissionslist.jsp(31,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f0.setValue("errors['groupName']");
      int _jspx_eval_ww_005fproperty_005f0 = _jspx_th_ww_005fproperty_005f0.doStartTag();
      if (_jspx_eval_ww_005fproperty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ww_005fproperty_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ww_005fproperty_005f0);
        }
        do {
          out.write("\n                ");
          out.write("\n                ");
          if (_jspx_meth_ww_005fif_005f0(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("\n            ");
          int evalDoAfterBody = _jspx_th_ww_005fproperty_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ww_005fproperty_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ww_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue.reuse(_jspx_th_ww_005fproperty_005f0);
      _jspx_th_ww_005fproperty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f0, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:if
    webwork.view.taglib.IfTag _jspx_th_ww_005fif_005f0 = (webwork.view.taglib.IfTag) _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.get(webwork.view.taglib.IfTag.class);
    boolean _jspx_th_ww_005fif_005f0_reused = false;
    try {
      _jspx_th_ww_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /includes/panels/permissionslist.jsp(33,16) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fif_005f0.setTest(".");
      int _jspx_eval_ww_005fif_005f0 = _jspx_th_ww_005fif_005f0.doStartTag();
      if (_jspx_eval_ww_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n                    <tr>\n                        <td class=\"fieldLabelArea formErrors\">&nbsp;</td>\n                        <td class=\"fieldValueArea formErrors\">\n                            <span class=\"errMsg\">");
          if (_jspx_meth_ww_005fproperty_005f1(_jspx_th_ww_005fif_005f0, _jspx_page_context))
            return true;
          out.write("</span>\n                        </td>\n                    </tr>\n                ");
          int evalDoAfterBody = _jspx_th_ww_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.reuse(_jspx_th_ww_005fif_005f0);
      _jspx_th_ww_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_ww_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f1 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f1_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f0);
      // /includes/panels/permissionslist.jsp(37,49) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f1.setValue(".");
      int _jspx_eval_ww_005fproperty_005f1 = _jspx_th_ww_005fproperty_005f1.doStartTag();
      if (_jspx_th_ww_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f1);
      _jspx_th_ww_005fproperty_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f1, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:if
    webwork.view.taglib.IfTag _jspx_th_ww_005fif_005f1 = (webwork.view.taglib.IfTag) _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.get(webwork.view.taglib.IfTag.class);
    boolean _jspx_th_ww_005fif_005f1_reused = false;
    try {
      _jspx_th_ww_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /includes/panels/permissionslist.jsp(43,41) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fif_005f1.setTest("errors['groupName']");
      int _jspx_eval_ww_005fif_005f1 = _jspx_th_ww_005fif_005f1.doStartTag();
      if (_jspx_eval_ww_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" formErrors");
          int evalDoAfterBody = _jspx_th_ww_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.reuse(_jspx_th_ww_005fif_005f1);
      _jspx_th_ww_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_ww_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f3 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f3_reused = false;
    try {
      _jspx_th_ww_005ftext_005f3.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /includes/panels/permissionslist.jsp(44,20) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f3.setName("'admin.common.words.group'");
      int _jspx_eval_ww_005ftext_005f3 = _jspx_th_ww_005ftext_005f3.doStartTag();
      if (_jspx_th_ww_005ftext_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f3);
      _jspx_th_ww_005ftext_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f3, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:if
    webwork.view.taglib.IfTag _jspx_th_ww_005fif_005f2 = (webwork.view.taglib.IfTag) _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.get(webwork.view.taglib.IfTag.class);
    boolean _jspx_th_ww_005fif_005f2_reused = false;
    try {
      _jspx_th_ww_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /includes/panels/permissionslist.jsp(46,75) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fif_005f2.setTest("errors['groupName']");
      int _jspx_eval_ww_005fif_005f2 = _jspx_th_ww_005fif_005f2.doStartTag();
      if (_jspx_eval_ww_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" formErrors");
          int evalDoAfterBody = _jspx_th_ww_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.reuse(_jspx_th_ww_005fif_005f2);
      _jspx_th_ww_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_ww_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f4 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f4_reused = false;
    try {
      _jspx_th_ww_005ftext_005f4.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /includes/panels/permissionslist.jsp(48,57) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f4.setName("'admin.globalpermissions.please.select.a.group'");
      int _jspx_eval_ww_005ftext_005f4 = _jspx_th_ww_005ftext_005f4.doStartTag();
      if (_jspx_th_ww_005ftext_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f4);
      _jspx_th_ww_005ftext_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f4, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f5 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f5_reused = false;
    try {
      _jspx_th_ww_005ftext_005f5.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /includes/panels/permissionslist.jsp(49,52) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f5.setName("'admin.common.words.anyone'");
      int _jspx_eval_ww_005ftext_005f5 = _jspx_th_ww_005ftext_005f5.doStartTag();
      if (_jspx_th_ww_005ftext_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f5);
      _jspx_th_ww_005ftext_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f5, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fcomponent_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:component
    webwork.view.taglib.ui.ComponentTag _jspx_th_ui_005fcomponent_005f0 = (webwork.view.taglib.ui.ComponentTag) _005fjspx_005ftagPool_005fui_005fcomponent_0026_005fvalue_005ftheme_005ftemplate_005fname_005fnobody.get(webwork.view.taglib.ui.ComponentTag.class);
    boolean _jspx_th_ui_005fcomponent_005f0_reused = false;
    try {
      _jspx_th_ui_005fcomponent_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fcomponent_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
      // /includes/panels/permissionslist.jsp(53,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fcomponent_005f0.setName("'action'");
      // /includes/panels/permissionslist.jsp(53,12) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fcomponent_005f0.setValue("'add'");
      // /includes/panels/permissionslist.jsp(53,12) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fcomponent_005f0.setTemplate("hidden.jsp");
      // /includes/panels/permissionslist.jsp(53,12) name = theme type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fcomponent_005f0.setTheme("'single'");
      int _jspx_eval_ui_005fcomponent_005f0 = _jspx_th_ui_005fcomponent_005f0.doStartTag();
      if (_jspx_th_ui_005fcomponent_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fui_005fcomponent_0026_005fvalue_005ftheme_005ftemplate_005fname_005fnobody.reuse(_jspx_th_ui_005fcomponent_005f0);
      _jspx_th_ui_005fcomponent_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ui_005fcomponent_005f0, _jsp_getInstanceManager(), _jspx_th_ui_005fcomponent_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f6 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f6_reused = false;
    try {
      _jspx_th_ww_005ftext_005f6.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f6.setParent(null);
      // /includes/panels/permissionslist.jsp(59,8) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f6.setName("'admin.errors.permissions.grant.admin.to.default.group.title'");
      int _jspx_eval_ww_005ftext_005f6 = _jspx_th_ww_005ftext_005f6.doStartTag();
      if (_jspx_th_ww_005ftext_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f6);
      _jspx_th_ww_005ftext_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f6, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f7 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f7_reused = false;
    try {
      _jspx_th_ww_005ftext_005f7.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f7.setParent(null);
      // /includes/panels/permissionslist.jsp(66,8) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f7.setName("'common.sharing.with.anyone.security.warning.title'");
      int _jspx_eval_ww_005ftext_005f7 = _jspx_th_ww_005ftext_005f7.doStartTag();
      if (_jspx_th_ww_005ftext_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f7);
      _jspx_th_ww_005ftext_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f7, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f8 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f8_reused = false;
    try {
      _jspx_th_ww_005ftext_005f8.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f8.setParent(null);
      // /includes/panels/permissionslist.jsp(69,8) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f8.setName("'common.sharing.with.anyone.security.warning'");
      int _jspx_eval_ww_005ftext_005f8 = _jspx_th_ww_005ftext_005f8.doStartTag();
      if (_jspx_th_ww_005ftext_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f8);
      _jspx_th_ww_005ftext_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f8, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f8_reused);
    }
    return false;
  }
}
