# nvidia
env = GBM_BACKEND,nvidia-drm
env = DXVK_FILTER_DEVICE_NAME,NVIDIA GeForce RTX 4060
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# nvidia hardware VA-API hardware video acceleration
env = LIBVA_DRIVER_NAME,nvidia
env = NVD_BACKEND,direct
