[bar.main]
position           = "top"
background_opacity = 0.1
margin_h           = 0
margin_v           = 0
radius             = 0
start  = ["launcher", "clock", "cpu_temp", "cpu_usage", "ram", "active_window", "media"]
center = ["workspaces"]
end    = ["tray", "notifications", "battery", "volume", "brightness", "control-center"]

[widget.launcher]
glyph = "rocket"

[widget.clock]
format         = "{:%H:%M %a, %b %d}"
tooltip_format = "{:%H:%M %a, %b %d}"

[widget.workspaces]
labels_only_when_occupied = true

[widget.cpu_temp]
type    = "sysmon"
stat    = "cpu_temp"
display = "text"

[widget.cpu_usage]
type    = "sysmon"
stat    = "cpu_usage"
display = "text"

[widget.ram]
type    = "sysmon"
stat    = "ram_used"
display = "text"

[widget.active_window]
max_length   = 145
title_scroll = "on_hover"

[widget.media]
max_length   = 145
title_scroll = "on_hover"

[widget.tray]
pinned = ["Arch-Update"]
drawer = true

[widget.battery]
display_mode = "graphic"

[widget.volume]
show_label = false
