/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Generated at: 2024-10-09 09:01:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package jsp.secure.admin.views.importers;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class importlogs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005felse;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005felse = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue.release();
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fww_005felse.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n\n\n");
      if (_jspx_meth_ww_005fproperty_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_ww_005fproperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f0 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f0_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f0.setParent(null);
      // /secure/admin/views/importers/importlogs.jsp(5,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f0.setValue("importer");
      int _jspx_eval_ww_005fproperty_005f0 = _jspx_th_ww_005fproperty_005f0.doStartTag();
      if (_jspx_eval_ww_005fproperty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ww_005fproperty_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ww_005fproperty_005f0);
        }
        do {
          out.write("\n\n<table class=\"grid\" style=\"width: 80%; margin: 10px auto;\">\n    <tr>\n        <th>");
          if (_jspx_meth_ww_005ftext_005f0(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("</th>\n        <th>");
          if (_jspx_meth_ww_005ftext_005f1(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("</th>\n    </tr>\n    <tr>\n        <td>");
          if (_jspx_meth_ww_005ftext_005f2(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("</td>\n        <td>");
          if (_jspx_meth_ww_005fproperty_005f1(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write(' ');
          if (_jspx_meth_ww_005fproperty_005f2(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("</td>\n    </tr>\n    <tr>\n        <td>");
          if (_jspx_meth_ww_005ftext_005f3(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("</td>\n        <td>");
          if (_jspx_meth_ww_005fproperty_005f3(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("</td>\n    </tr>\n    ");
          if (_jspx_meth_ww_005fproperty_005f4(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("\n    ");
          if (_jspx_meth_ww_005fif_005f1(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("\n    ");
          if (_jspx_meth_ww_005fif_005f2(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("\n    ");
          if (_jspx_meth_ww_005fif_005f3(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("\n    ");
          if (_jspx_meth_ww_005fif_005f4(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("\n\n    <tr>\n        <td>");
          if (_jspx_meth_ww_005ftext_005f9(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("</td>\n        <td>");
          if (_jspx_meth_ww_005fproperty_005f10(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("</td>\n    </tr>\n    ");
          if (_jspx_meth_ww_005fif_005f5(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("\n\n    ");
          if (_jspx_meth_ww_005fif_005f6(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("\n    ");
          if (_jspx_meth_ww_005fif_005f7(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("\n    ");
          if (_jspx_meth_ww_005fif_005f8(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("\n\n\n\n</table>\n\n\n<pre class=\"codearea\">\n<h4>");
          if (_jspx_meth_ww_005ftext_005f14(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("</h4>\n");
          if (_jspx_meth_ww_005fif_005f9(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          if (_jspx_meth_ww_005felse_005f0(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("\n</pre>\n    ");
          if (_jspx_meth_ww_005fif_005f10(_jspx_th_ww_005fproperty_005f0, _jspx_page_context))
            return true;
          out.write("\n<script language=\"JavaScript\" type=\"text/javascript\">\n<!--\n    function scrollDown()\n    {\n        try\n        {\n            var importLogs = document.getElementById(\"importLogs\");\n            if (importLogs.scrollHeight)\n                importLogs.scrollTop = importLogs.scrollHeight;\n        }\n        catch (e)\n        {\n            // do nothing;\n        }\n    }\n\n    setTimeout('scrollDown();', 1);\n//-->\n</script>\n\n");
          int evalDoAfterBody = _jspx_th_ww_005fproperty_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ww_005fproperty_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ww_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue.reuse(_jspx_th_ww_005fproperty_005f0);
      _jspx_th_ww_005fproperty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f0, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f0 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f0_reused = false;
    try {
      _jspx_th_ww_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(9,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f0.setName("'admin.importlogs.statistic'");
      int _jspx_eval_ww_005ftext_005f0 = _jspx_th_ww_005ftext_005f0.doStartTag();
      if (_jspx_th_ww_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f0);
      _jspx_th_ww_005ftext_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f0, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f1 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f1_reused = false;
    try {
      _jspx_th_ww_005ftext_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(10,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f1.setName("'admin.importlogs.data'");
      int _jspx_eval_ww_005ftext_005f1 = _jspx_th_ww_005ftext_005f1.doStartTag();
      if (_jspx_th_ww_005ftext_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f1);
      _jspx_th_ww_005ftext_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f1, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f2 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f2_reused = false;
    try {
      _jspx_th_ww_005ftext_005f2.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(13,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f2.setName("'admin.importlogs.elapsed.time'");
      int _jspx_eval_ww_005ftext_005f2 = _jspx_th_ww_005ftext_005f2.doStartTag();
      if (_jspx_th_ww_005ftext_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f2);
      _jspx_th_ww_005ftext_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f2, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f1 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f1_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(14,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f1.setValue("./stats/formattedTime");
      int _jspx_eval_ww_005fproperty_005f1 = _jspx_th_ww_005fproperty_005f1.doStartTag();
      if (_jspx_th_ww_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f1);
      _jspx_th_ww_005fproperty_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f1, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f2 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f2_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f2.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(14,58) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f2.setValue("./stats/estimateRemaining");
      int _jspx_eval_ww_005fproperty_005f2 = _jspx_th_ww_005fproperty_005f2.doStartTag();
      if (_jspx_th_ww_005fproperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f2);
      _jspx_th_ww_005fproperty_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f2, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f3 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f3_reused = false;
    try {
      _jspx_th_ww_005ftext_005f3.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(17,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f3.setName("'admin.importlogs.import.rate'");
      int _jspx_eval_ww_005ftext_005f3 = _jspx_th_ww_005ftext_005f3.doStartTag();
      if (_jspx_th_ww_005ftext_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f3);
      _jspx_th_ww_005ftext_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f3, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f3 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f3_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f3.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(18,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f3.setValue("./stats/importRate");
      int _jspx_eval_ww_005fproperty_005f3 = _jspx_th_ww_005fproperty_005f3.doStartTag();
      if (_jspx_th_ww_005fproperty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f3);
      _jspx_th_ww_005fproperty_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f3, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f4 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f4_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f4.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(20,4) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f4.setValue("./stats/failures");
      int _jspx_eval_ww_005fproperty_005f4 = _jspx_th_ww_005fproperty_005f4.doStartTag();
      if (_jspx_eval_ww_005fproperty_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ww_005fproperty_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ww_005fproperty_005f4);
        }
        do {
          out.write("\n    <tr ");
          if (_jspx_meth_ww_005fif_005f0(_jspx_th_ww_005fproperty_005f4, _jspx_page_context))
            return true;
          out.write(">\n        <td>");
          if (_jspx_meth_ww_005ftext_005f4(_jspx_th_ww_005fproperty_005f4, _jspx_page_context))
            return true;
          out.write("</td>\n        <td>");
          if (_jspx_meth_ww_005fproperty_005f5(_jspx_th_ww_005fproperty_005f4, _jspx_page_context))
            return true;
          out.write("</td>\n    </tr>\n    ");
          int evalDoAfterBody = _jspx_th_ww_005fproperty_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ww_005fproperty_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ww_005fproperty_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue.reuse(_jspx_th_ww_005fproperty_005f4);
      _jspx_th_ww_005fproperty_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f4, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:if
    webwork.view.taglib.IfTag _jspx_th_ww_005fif_005f0 = (webwork.view.taglib.IfTag) _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.get(webwork.view.taglib.IfTag.class);
    boolean _jspx_th_ww_005fif_005f0_reused = false;
    try {
      _jspx_th_ww_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f4);
      // /secure/admin/views/importers/importlogs.jsp(21,8) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fif_005f0.setTest(". > 0");
      int _jspx_eval_ww_005fif_005f0 = _jspx_th_ww_005fif_005f0.doStartTag();
      if (_jspx_eval_ww_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("class=\"red-highlight\"");
          int evalDoAfterBody = _jspx_th_ww_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.reuse(_jspx_th_ww_005fif_005f0);
      _jspx_th_ww_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_ww_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f4 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f4_reused = false;
    try {
      _jspx_th_ww_005ftext_005f4.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f4);
      // /secure/admin/views/importers/importlogs.jsp(22,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f4.setName("'admin.importlogs.failures'");
      int _jspx_eval_ww_005ftext_005f4 = _jspx_th_ww_005ftext_005f4.doStartTag();
      if (_jspx_th_ww_005ftext_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f4);
      _jspx_th_ww_005ftext_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f4, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f5 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f5_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f5.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f4);
      // /secure/admin/views/importers/importlogs.jsp(23,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f5.setValue(".");
      int _jspx_eval_ww_005fproperty_005f5 = _jspx_th_ww_005fproperty_005f5.doStartTag();
      if (_jspx_th_ww_005fproperty_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f5);
      _jspx_th_ww_005fproperty_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f5, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:if
    webwork.view.taglib.IfTag _jspx_th_ww_005fif_005f1 = (webwork.view.taglib.IfTag) _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.get(webwork.view.taglib.IfTag.class);
    boolean _jspx_th_ww_005fif_005f1_reused = false;
    try {
      _jspx_th_ww_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(26,4) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fif_005f1.setTest("./stats/usersImported > 0");
      int _jspx_eval_ww_005fif_005f1 = _jspx_th_ww_005fif_005f1.doStartTag();
      if (_jspx_eval_ww_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n    <tr>\n        <td>");
          if (_jspx_meth_ww_005ftext_005f5(_jspx_th_ww_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</td>\n        <td>");
          if (_jspx_meth_ww_005fproperty_005f6(_jspx_th_ww_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</td>\n    </tr>\n    ");
          int evalDoAfterBody = _jspx_th_ww_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.reuse(_jspx_th_ww_005fif_005f1);
      _jspx_th_ww_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_ww_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f5 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f5_reused = false;
    try {
      _jspx_th_ww_005ftext_005f5.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f1);
      // /secure/admin/views/importers/importlogs.jsp(28,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f5.setName("'admin.importlogs.users.imported'");
      int _jspx_eval_ww_005ftext_005f5 = _jspx_th_ww_005ftext_005f5.doStartTag();
      if (_jspx_th_ww_005ftext_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f5);
      _jspx_th_ww_005ftext_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f5, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f6 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f6_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f6.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f1);
      // /secure/admin/views/importers/importlogs.jsp(29,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f6.setValue("./stats/usersImported");
      int _jspx_eval_ww_005fproperty_005f6 = _jspx_th_ww_005fproperty_005f6.doStartTag();
      if (_jspx_th_ww_005fproperty_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f6);
      _jspx_th_ww_005fproperty_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f6, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:if
    webwork.view.taglib.IfTag _jspx_th_ww_005fif_005f2 = (webwork.view.taglib.IfTag) _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.get(webwork.view.taglib.IfTag.class);
    boolean _jspx_th_ww_005fif_005f2_reused = false;
    try {
      _jspx_th_ww_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(32,4) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fif_005f2.setTest("./stats/projectsImported > 0");
      int _jspx_eval_ww_005fif_005f2 = _jspx_th_ww_005fif_005f2.doStartTag();
      if (_jspx_eval_ww_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n    <tr>\n        <td>");
          if (_jspx_meth_ww_005ftext_005f6(_jspx_th_ww_005fif_005f2, _jspx_page_context))
            return true;
          out.write("</td>\n        <td>");
          if (_jspx_meth_ww_005fproperty_005f7(_jspx_th_ww_005fif_005f2, _jspx_page_context))
            return true;
          out.write("</td>\n    </tr>\n    ");
          int evalDoAfterBody = _jspx_th_ww_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.reuse(_jspx_th_ww_005fif_005f2);
      _jspx_th_ww_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_ww_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f6 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f6_reused = false;
    try {
      _jspx_th_ww_005ftext_005f6.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f2);
      // /secure/admin/views/importers/importlogs.jsp(34,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f6.setName("'admin.importlogs.projects.imported'");
      int _jspx_eval_ww_005ftext_005f6 = _jspx_th_ww_005ftext_005f6.doStartTag();
      if (_jspx_th_ww_005ftext_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f6);
      _jspx_th_ww_005ftext_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f6, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f7 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f7_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f7.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f2);
      // /secure/admin/views/importers/importlogs.jsp(35,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f7.setValue("./stats/projectsImported");
      int _jspx_eval_ww_005fproperty_005f7 = _jspx_th_ww_005fproperty_005f7.doStartTag();
      if (_jspx_th_ww_005fproperty_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f7);
      _jspx_th_ww_005fproperty_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f7, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:if
    webwork.view.taglib.IfTag _jspx_th_ww_005fif_005f3 = (webwork.view.taglib.IfTag) _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.get(webwork.view.taglib.IfTag.class);
    boolean _jspx_th_ww_005fif_005f3_reused = false;
    try {
      _jspx_th_ww_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(38,4) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fif_005f3.setTest("./stats/versionsImported > 0");
      int _jspx_eval_ww_005fif_005f3 = _jspx_th_ww_005fif_005f3.doStartTag();
      if (_jspx_eval_ww_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n    <tr>\n        <td>");
          if (_jspx_meth_ww_005ftext_005f7(_jspx_th_ww_005fif_005f3, _jspx_page_context))
            return true;
          out.write("</td>\n        <td>");
          if (_jspx_meth_ww_005fproperty_005f8(_jspx_th_ww_005fif_005f3, _jspx_page_context))
            return true;
          out.write("</td>\n    </tr>\n    ");
          int evalDoAfterBody = _jspx_th_ww_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.reuse(_jspx_th_ww_005fif_005f3);
      _jspx_th_ww_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_ww_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f7 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f7_reused = false;
    try {
      _jspx_th_ww_005ftext_005f7.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f3);
      // /secure/admin/views/importers/importlogs.jsp(40,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f7.setName("'admin.importlogs.versions.imported'");
      int _jspx_eval_ww_005ftext_005f7 = _jspx_th_ww_005ftext_005f7.doStartTag();
      if (_jspx_th_ww_005ftext_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f7);
      _jspx_th_ww_005ftext_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f7, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f8 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f8_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f8.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f3);
      // /secure/admin/views/importers/importlogs.jsp(41,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f8.setValue("./stats/versionsImported");
      int _jspx_eval_ww_005fproperty_005f8 = _jspx_th_ww_005fproperty_005f8.doStartTag();
      if (_jspx_th_ww_005fproperty_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f8);
      _jspx_th_ww_005fproperty_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f8, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:if
    webwork.view.taglib.IfTag _jspx_th_ww_005fif_005f4 = (webwork.view.taglib.IfTag) _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.get(webwork.view.taglib.IfTag.class);
    boolean _jspx_th_ww_005fif_005f4_reused = false;
    try {
      _jspx_th_ww_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(44,4) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fif_005f4.setTest("./stats/componentsImported > 0");
      int _jspx_eval_ww_005fif_005f4 = _jspx_th_ww_005fif_005f4.doStartTag();
      if (_jspx_eval_ww_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n    <tr>\n        <td>");
          if (_jspx_meth_ww_005ftext_005f8(_jspx_th_ww_005fif_005f4, _jspx_page_context))
            return true;
          out.write("</td>\n        <td>");
          if (_jspx_meth_ww_005fproperty_005f9(_jspx_th_ww_005fif_005f4, _jspx_page_context))
            return true;
          out.write("</td>\n    </tr>\n    ");
          int evalDoAfterBody = _jspx_th_ww_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.reuse(_jspx_th_ww_005fif_005f4);
      _jspx_th_ww_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_ww_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f8 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f8_reused = false;
    try {
      _jspx_th_ww_005ftext_005f8.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f4);
      // /secure/admin/views/importers/importlogs.jsp(46,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f8.setName("'admin.importlogs.components.imported'");
      int _jspx_eval_ww_005ftext_005f8 = _jspx_th_ww_005ftext_005f8.doStartTag();
      if (_jspx_th_ww_005ftext_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f8);
      _jspx_th_ww_005ftext_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f8, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f9 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f9_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f9.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f4);
      // /secure/admin/views/importers/importlogs.jsp(47,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f9.setValue("./stats/componentsImported");
      int _jspx_eval_ww_005fproperty_005f9 = _jspx_th_ww_005fproperty_005f9.doStartTag();
      if (_jspx_th_ww_005fproperty_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f9);
      _jspx_th_ww_005fproperty_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f9, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f9 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f9_reused = false;
    try {
      _jspx_th_ww_005ftext_005f9.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(52,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f9.setName("'admin.importlogs.issues.imported'");
      int _jspx_eval_ww_005ftext_005f9 = _jspx_th_ww_005ftext_005f9.doStartTag();
      if (_jspx_th_ww_005ftext_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f9);
      _jspx_th_ww_005ftext_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f9, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f10 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f10_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f10.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(53,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f10.setValue("./stats/issuesImported");
      int _jspx_eval_ww_005fproperty_005f10 = _jspx_th_ww_005fproperty_005f10.doStartTag();
      if (_jspx_th_ww_005fproperty_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f10);
      _jspx_th_ww_005fproperty_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f10, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:if
    webwork.view.taglib.IfTag _jspx_th_ww_005fif_005f5 = (webwork.view.taglib.IfTag) _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.get(webwork.view.taglib.IfTag.class);
    boolean _jspx_th_ww_005fif_005f5_reused = false;
    try {
      _jspx_th_ww_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(55,4) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fif_005f5.setTest("./stats/customfieldsImported > 0");
      int _jspx_eval_ww_005fif_005f5 = _jspx_th_ww_005fif_005f5.doStartTag();
      if (_jspx_eval_ww_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n    <tr>\n        <td>");
          if (_jspx_meth_ww_005ftext_005f10(_jspx_th_ww_005fif_005f5, _jspx_page_context))
            return true;
          out.write("</td>\n        <td>");
          if (_jspx_meth_ww_005fproperty_005f11(_jspx_th_ww_005fif_005f5, _jspx_page_context))
            return true;
          out.write("</td>\n    </tr>\n    ");
          int evalDoAfterBody = _jspx_th_ww_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.reuse(_jspx_th_ww_005fif_005f5);
      _jspx_th_ww_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_ww_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f10 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f10_reused = false;
    try {
      _jspx_th_ww_005ftext_005f10.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f5);
      // /secure/admin/views/importers/importlogs.jsp(57,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f10.setName("'admin.importlogs.new.custom.fields'");
      int _jspx_eval_ww_005ftext_005f10 = _jspx_th_ww_005ftext_005f10.doStartTag();
      if (_jspx_th_ww_005ftext_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f10);
      _jspx_th_ww_005ftext_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f10, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f11 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f11_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f11.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f5);
      // /secure/admin/views/importers/importlogs.jsp(58,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f11.setValue("./stats/customfieldsImported");
      int _jspx_eval_ww_005fproperty_005f11 = _jspx_th_ww_005fproperty_005f11.doStartTag();
      if (_jspx_th_ww_005fproperty_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f11);
      _jspx_th_ww_005fproperty_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f11, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:if
    webwork.view.taglib.IfTag _jspx_th_ww_005fif_005f6 = (webwork.view.taglib.IfTag) _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.get(webwork.view.taglib.IfTag.class);
    boolean _jspx_th_ww_005fif_005f6_reused = false;
    try {
      _jspx_th_ww_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(62,4) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fif_005f6.setTest("./stats/issuetypesImported > 0");
      int _jspx_eval_ww_005fif_005f6 = _jspx_th_ww_005fif_005f6.doStartTag();
      if (_jspx_eval_ww_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n    <tr>\n        <td>");
          if (_jspx_meth_ww_005ftext_005f11(_jspx_th_ww_005fif_005f6, _jspx_page_context))
            return true;
          out.write("</td>\n        <td>");
          if (_jspx_meth_ww_005fproperty_005f12(_jspx_th_ww_005fif_005f6, _jspx_page_context))
            return true;
          out.write("</td>\n    </tr>\n    ");
          int evalDoAfterBody = _jspx_th_ww_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.reuse(_jspx_th_ww_005fif_005f6);
      _jspx_th_ww_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_ww_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f6, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f11 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f11_reused = false;
    try {
      _jspx_th_ww_005ftext_005f11.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f6);
      // /secure/admin/views/importers/importlogs.jsp(64,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f11.setName("'admin.importlogs.new.issue.types'");
      int _jspx_eval_ww_005ftext_005f11 = _jspx_th_ww_005ftext_005f11.doStartTag();
      if (_jspx_th_ww_005ftext_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f11);
      _jspx_th_ww_005ftext_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f11, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f6, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f12 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f12_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f12.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f6);
      // /secure/admin/views/importers/importlogs.jsp(65,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f12.setValue("./stats/issuetypesImported");
      int _jspx_eval_ww_005fproperty_005f12 = _jspx_th_ww_005fproperty_005f12.doStartTag();
      if (_jspx_th_ww_005fproperty_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f12);
      _jspx_th_ww_005fproperty_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f12, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fif_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:if
    webwork.view.taglib.IfTag _jspx_th_ww_005fif_005f7 = (webwork.view.taglib.IfTag) _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.get(webwork.view.taglib.IfTag.class);
    boolean _jspx_th_ww_005fif_005f7_reused = false;
    try {
      _jspx_th_ww_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fif_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(68,4) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fif_005f7.setTest("./stats/resolutionsImported > 0");
      int _jspx_eval_ww_005fif_005f7 = _jspx_th_ww_005fif_005f7.doStartTag();
      if (_jspx_eval_ww_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n    <tr>\n        <td>");
          if (_jspx_meth_ww_005ftext_005f12(_jspx_th_ww_005fif_005f7, _jspx_page_context))
            return true;
          out.write("</td>\n        <td>");
          if (_jspx_meth_ww_005fproperty_005f13(_jspx_th_ww_005fif_005f7, _jspx_page_context))
            return true;
          out.write("</td>\n    </tr>\n    ");
          int evalDoAfterBody = _jspx_th_ww_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.reuse(_jspx_th_ww_005fif_005f7);
      _jspx_th_ww_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_ww_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f7, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f12 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f12_reused = false;
    try {
      _jspx_th_ww_005ftext_005f12.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f7);
      // /secure/admin/views/importers/importlogs.jsp(70,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f12.setName("'admin.importlogs.new.resolutions'");
      int _jspx_eval_ww_005ftext_005f12 = _jspx_th_ww_005ftext_005f12.doStartTag();
      if (_jspx_th_ww_005ftext_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f12);
      _jspx_th_ww_005ftext_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f12, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f13(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f7, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f13 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f13_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f13.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f13.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f7);
      // /secure/admin/views/importers/importlogs.jsp(71,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f13.setValue("./stats/resolutionsImported");
      int _jspx_eval_ww_005fproperty_005f13 = _jspx_th_ww_005fproperty_005f13.doStartTag();
      if (_jspx_th_ww_005fproperty_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f13);
      _jspx_th_ww_005fproperty_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f13, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f13_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fif_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:if
    webwork.view.taglib.IfTag _jspx_th_ww_005fif_005f8 = (webwork.view.taglib.IfTag) _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.get(webwork.view.taglib.IfTag.class);
    boolean _jspx_th_ww_005fif_005f8_reused = false;
    try {
      _jspx_th_ww_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fif_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(74,4) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fif_005f8.setTest("./stats/prioritiesImported > 0");
      int _jspx_eval_ww_005fif_005f8 = _jspx_th_ww_005fif_005f8.doStartTag();
      if (_jspx_eval_ww_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n    <tr>\n        <td>");
          if (_jspx_meth_ww_005ftext_005f13(_jspx_th_ww_005fif_005f8, _jspx_page_context))
            return true;
          out.write("</td>\n        <td>");
          if (_jspx_meth_ww_005fproperty_005f14(_jspx_th_ww_005fif_005f8, _jspx_page_context))
            return true;
          out.write("</td>\n    </tr>\n    ");
          int evalDoAfterBody = _jspx_th_ww_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.reuse(_jspx_th_ww_005fif_005f8);
      _jspx_th_ww_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_ww_005fif_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f13(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f8, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f13 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f13_reused = false;
    try {
      _jspx_th_ww_005ftext_005f13.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f13.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f8);
      // /secure/admin/views/importers/importlogs.jsp(76,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f13.setName("'admin.importlogs.new.priorities'");
      int _jspx_eval_ww_005ftext_005f13 = _jspx_th_ww_005ftext_005f13.doStartTag();
      if (_jspx_th_ww_005ftext_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f13);
      _jspx_th_ww_005ftext_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f13, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f13_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f14(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f8, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f14 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f14_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f14.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f14.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f8);
      // /secure/admin/views/importers/importlogs.jsp(77,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f14.setValue("./stats/prioritiesImported");
      int _jspx_eval_ww_005fproperty_005f14 = _jspx_th_ww_005fproperty_005f14.doStartTag();
      if (_jspx_th_ww_005fproperty_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f14);
      _jspx_th_ww_005fproperty_005f14_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f14, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f14_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f14(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f14 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f14_reused = false;
    try {
      _jspx_th_ww_005ftext_005f14.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f14.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(87,4) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f14.setName("'admin.importlogs.import.logs'");
      int _jspx_eval_ww_005ftext_005f14 = _jspx_th_ww_005ftext_005f14.doStartTag();
      if (_jspx_th_ww_005ftext_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f14);
      _jspx_th_ww_005ftext_005f14_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f14, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f14_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fif_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:if
    webwork.view.taglib.IfTag _jspx_th_ww_005fif_005f9 = (webwork.view.taglib.IfTag) _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.get(webwork.view.taglib.IfTag.class);
    boolean _jspx_th_ww_005fif_005f9_reused = false;
    try {
      _jspx_th_ww_005fif_005f9.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fif_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(88,0) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fif_005f9.setTest("./finished == true");
      int _jspx_eval_ww_005fif_005f9 = _jspx_th_ww_005fif_005f9.doStartTag();
      if (_jspx_eval_ww_005fif_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          if (_jspx_meth_ww_005fproperty_005f15(_jspx_th_ww_005fif_005f9, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_ww_005fif_005f9.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005fif_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.reuse(_jspx_th_ww_005fif_005f9);
      _jspx_th_ww_005fif_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fif_005f9, _jsp_getInstanceManager(), _jspx_th_ww_005fif_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f15(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f9, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f15 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f15_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f15.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f15.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f9);
      // /secure/admin/views/importers/importlogs.jsp(88,33) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f15.setValue("./log/importLog");
      int _jspx_eval_ww_005fproperty_005f15 = _jspx_th_ww_005fproperty_005f15.doStartTag();
      if (_jspx_th_ww_005fproperty_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f15);
      _jspx_th_ww_005fproperty_005f15_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f15, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f15_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005felse_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:else
    webwork.view.taglib.ElseTag _jspx_th_ww_005felse_005f0 = (webwork.view.taglib.ElseTag) _005fjspx_005ftagPool_005fww_005felse.get(webwork.view.taglib.ElseTag.class);
    boolean _jspx_th_ww_005felse_005f0_reused = false;
    try {
      _jspx_th_ww_005felse_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ww_005felse_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      int _jspx_eval_ww_005felse_005f0 = _jspx_th_ww_005felse_005f0.doStartTag();
      if (_jspx_eval_ww_005felse_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<textarea readonly=\"readonly\" id=\"importLogs\" name=\"importLogs\">");
          if (_jspx_meth_ww_005fproperty_005f16(_jspx_th_ww_005felse_005f0, _jspx_page_context))
            return true;
          out.write("</textarea>");
          int evalDoAfterBody = _jspx_th_ww_005felse_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005felse_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005felse.reuse(_jspx_th_ww_005felse_005f0);
      _jspx_th_ww_005felse_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005felse_005f0, _jsp_getInstanceManager(), _jspx_th_ww_005felse_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fproperty_005f16(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005felse_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:property
    webwork.view.taglib.PropertyTag _jspx_th_ww_005fproperty_005f16 = (webwork.view.taglib.PropertyTag) _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.get(webwork.view.taglib.PropertyTag.class);
    boolean _jspx_th_ww_005fproperty_005f16_reused = false;
    try {
      _jspx_th_ww_005fproperty_005f16.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fproperty_005f16.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005felse_005f0);
      // /secure/admin/views/importers/importlogs.jsp(88,153) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fproperty_005f16.setValue("./log/shortenedLog");
      int _jspx_eval_ww_005fproperty_005f16 = _jspx_th_ww_005fproperty_005f16.doStartTag();
      if (_jspx_th_ww_005fproperty_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_ww_005fproperty_005f16);
      _jspx_th_ww_005fproperty_005f16_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fproperty_005f16, _jsp_getInstanceManager(), _jspx_th_ww_005fproperty_005f16_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005fif_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fproperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:if
    webwork.view.taglib.IfTag _jspx_th_ww_005fif_005f10 = (webwork.view.taglib.IfTag) _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.get(webwork.view.taglib.IfTag.class);
    boolean _jspx_th_ww_005fif_005f10_reused = false;
    try {
      _jspx_th_ww_005fif_005f10.setPageContext(_jspx_page_context);
      _jspx_th_ww_005fif_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fproperty_005f0);
      // /secure/admin/views/importers/importlogs.jsp(90,4) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005fif_005f10.setTest("./log/logShortened == true && ./finished == false");
      int _jspx_eval_ww_005fif_005f10 = _jspx_th_ww_005fif_005f10.doStartTag();
      if (_jspx_eval_ww_005fif_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n    <div class=\"informationbox\">\n        ");
          if (_jspx_meth_ww_005ftext_005f15(_jspx_th_ww_005fif_005f10, _jspx_page_context))
            return true;
          out.write("\n    </div>\n");
          int evalDoAfterBody = _jspx_th_ww_005fif_005f10.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ww_005fif_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005fif_0026_005ftest.reuse(_jspx_th_ww_005fif_005f10);
      _jspx_th_ww_005fif_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005fif_005f10, _jsp_getInstanceManager(), _jspx_th_ww_005fif_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f15(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005fif_005f10, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f15 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    boolean _jspx_th_ww_005ftext_005f15_reused = false;
    try {
      _jspx_th_ww_005ftext_005f15.setPageContext(_jspx_page_context);
      _jspx_th_ww_005ftext_005f15.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005fif_005f10);
      // /secure/admin/views/importers/importlogs.jsp(92,8) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ww_005ftext_005f15.setName("'admin.importlogs.please.note'");
      int _jspx_eval_ww_005ftext_005f15 = _jspx_th_ww_005ftext_005f15.doStartTag();
      if (_jspx_th_ww_005ftext_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f15);
      _jspx_th_ww_005ftext_005f15_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ww_005ftext_005f15, _jsp_getInstanceManager(), _jspx_th_ww_005ftext_005f15_reused);
    }
    return false;
  }
}
